SELECT U.CARRIER_ID, U.ACCOUNT_ID, U.EMPLOYER_GROUP_ID, CAGM.CLT_ID CLIENT_ID, U.SRC_ENV_SK FROM $D_CAG_SCHEMA.D_CAG U
INNER JOIN $CAG_MASK_SCHEMA.CLIENT_ID_CAG_MASK CAGM
ON U.CARRIER_ID=CAGM.GRP_HRCHY_LVL_1_ID AND
U.ACCOUNT_ID=CAGM.GRP_HRCHY_LVL_2_ID AND
U.EMPLOYER_GROUP_ID=CAGM.GRP_HRCHY_LVL_3_ID
UNION
SELECT U.CARRIER_ID, U.ACCOUNT_ID, U.EMPLOYER_GROUP_ID, CAGM.CLT_ID CLIENT_ID, U.SRC_ENV_SK FROM $D_CAG_SCHEMA.D_CAG U
INNER JOIN $CAG_MASK_SCHEMA.CLIENT_ID_CAG_MASK CAGM 
ON U.CARRIER_ID=CAGM.GRP_HRCHY_LVL_1_ID AND
U.ACCOUNT_ID=CAGM.GRP_HRCHY_LVL_2_ID AND CAGM.GRP_HRCHY_LVL_3_ID= '*' AND
NOT EXISTS ( SELECT 1 FROM
       (SELECT U.CARRIER_ID, U.ACCOUNT_ID, U.EMPLOYER_GROUP_ID, CAGM.CLT_ID CLIENT_ID, U.SRC_ENV_SK FROM $D_CAG_SCHEMA.D_CAG U
       INNER JOIN $CAG_MASK_SCHEMA.CLIENT_ID_CAG_MASK CAGM
       ON U.CARRIER_ID=CAGM.GRP_HRCHY_LVL_1_ID AND
       U.ACCOUNT_ID=CAGM.GRP_HRCHY_LVL_2_ID AND
       U.EMPLOYER_GROUP_ID=CAGM.GRP_HRCHY_LVL_3_ID ) EX
       WHERE EX.CARRIER_ID= U.CARRIER_ID AND EX.ACCOUNT_ID= U.ACCOUNT_ID AND EX.EMPLOYER_GROUP_ID =U.EMPLOYER_GROUP_ID )
UNION
SELECT U.CARRIER_ID, U.ACCOUNT_ID, U.EMPLOYER_GROUP_ID, CAGM.CLT_ID CLIENT_ID, U.SRC_ENV_SK FROM $D_CAG_SCHEMA.D_CAG U
INNER JOIN $CAG_MASK_SCHEMA.CLIENT_ID_CAG_MASK CAGM
ON U.CARRIER_ID=CAGM.GRP_HRCHY_LVL_1_ID AND CAGM.GRP_HRCHY_LVL_2_ID='*' AND CAGM.GRP_HRCHY_LVL_3_ID='*' AND
NOT EXISTS ( SELECT 1 FROM
       (SELECT U.CARRIER_ID, U.ACCOUNT_ID, U.EMPLOYER_GROUP_ID, CAGM.CLT_ID CLIENT_ID, U.SRC_ENV_SK FROM $D_CAG_SCHEMA.D_CAG U
       INNER JOIN $CAG_MASK_SCHEMA.CLIENT_ID_CAG_MASK CAGM
       ON U.CARRIER_ID=CAGM.GRP_HRCHY_LVL_1_ID AND
       U.ACCOUNT_ID=CAGM.GRP_HRCHY_LVL_2_ID AND
       U.EMPLOYER_GROUP_ID=CAGM.GRP_HRCHY_LVL_3_ID ) EX
       WHERE EX.CARRIER_ID= U.CARRIER_ID AND EX.ACCOUNT_ID= U.ACCOUNT_ID AND EX.EMPLOYER_GROUP_ID =U.EMPLOYER_GROUP_ID ) AND
NOT EXISTS ( SELECT 1 FROM
                     (SELECT U.CARRIER_ID, U.ACCOUNT_ID, U.EMPLOYER_GROUP_ID, CAGM.CLT_ID CLIENT_ID, U.SRC_ENV_SK FROM $D_CAG_SCHEMA.D_CAG U
                     INNER JOIN $CAG_MASK_SCHEMA.CLIENT_ID_CAG_MASK CAGM 
                     ON U.CARRIER_ID=CAGM.GRP_HRCHY_LVL_1_ID AND
                     U.ACCOUNT_ID=CAGM.GRP_HRCHY_LVL_2_ID AND CAGM.GRP_HRCHY_LVL_3_ID= '*' AND
                     NOT EXISTS ( SELECT 1 FROM
                                  (SELECT U.CARRIER_ID, U.ACCOUNT_ID, U.EMPLOYER_GROUP_ID, CAGM.CLT_ID CLIENT_ID, U.SRC_ENV_SK FROM $D_CAG_SCHEMA.D_CAG U
                                  INNER JOIN $CAG_MASK_SCHEMA.CLIENT_ID_CAG_MASK CAGM
                                  ON U.CARRIER_ID=CAGM.GRP_HRCHY_LVL_1_ID AND
                                  U.ACCOUNT_ID=CAGM.GRP_HRCHY_LVL_2_ID AND
                                  U.EMPLOYER_GROUP_ID=CAGM.GRP_HRCHY_LVL_3_ID) EX
                                  WHERE EX.CARRIER_ID= U.CARRIER_ID AND EX.ACCOUNT_ID= U.ACCOUNT_ID AND EX.EMPLOYER_GROUP_ID =U.EMPLOYER_GROUP_ID )) E
                     WHERE E.CARRIER_ID= U.CARRIER_ID AND E.ACCOUNT_ID= U.ACCOUNT_ID AND E.EMPLOYER_GROUP_ID =U.EMPLOYER_GROUP_ID )
