SELECT rcex1p.rxclaimnbr
     , rcex1p.clmseqnbr
     , rcex1p.claimsts
     , rcex1p.carrierid
     , rcex1p.scarrierid
     , rcex1p.carrproc
     , rcex1p.accountid
     , rcex1p.acctbencde
     , rcex1p.versionnbr
     , rcex1p.groupid
     , rcex1p.groupplan
     , rcex1p.grpclibenf
     , rcex1p.groupsic
     , rcex1p.clmrespsts
     , rcex1p.memberid
     , rcex1p.mbrlstnme
     , rcex1p.mbrfstnme
     , rcex1p.mbrmdinit
     , rcex1p.mbrprsncde
     , rcex1p.mbrrelcde
     , rcex1p.mbrsex
     , rcex1p.mbrbirth
     , rcex1p.mbrage
     , rcex1p.mbrzip
     , rcex1p.socsecnbr
     , rcex1p.durkey
     , rcex1p.durflag
     , rcex1p.mbrfamlyid
     , rcex1p.mbrfamlind
     , rcex1p.mbrfamltyp
     , rcex1p.cobind
     , rcex1p.mbrplan
     , rcex1p.mbrprodcde
     , rcex1p.mbrridercd
     , rcex1p.carenetid
     , rcex1p.carequalid
     , rcex1p.carefacid
     , rcex1p.carefacnam
     , rcex1p.mbrpcphys
     , rcex1p.pprsfstnme
     , rcex1p.pprslstnme
     , rcex1p.pprsmdinit
     , rcex1p.pprsspccde
     , rcex1p.mbraltinfl
     , rcex1p.mbraltincd
     , rcex1p.mbraltinid
     , rcex1p.mbrmeddte
     , rcex1p.mbrmedtype
     , rcex1p.mbrhiccde
     , rcex1p.cardholder
     , rcex1p.patlastnme
     , rcex1p.patfrstnme
     , rcex1p.personcde
     , rcex1p.relationcd
     , rcex1p.sexcode
     , rcex1p.birthdte
     , rcex1p.eligclarif
     , rcex1p.custloc
     , rcex1p.prmcareprv
     , rcex1p.prmcareprq
     , rcex1p.facilityid
     , rcex1p.othcoverag
     , rcex1p.binnumber
     , rcex1p.processor
     , rcex1p.groupnbr
     , rcex1p.transcde
     , rcex1p.datesbm
     , rcex1p.timesbm
     , rcex1p.orgpdsbmdt
     , rcex1p.rvdatesbm
     , rcex1p.clmcounter
     , rcex1p.genericctr
     , rcex1p.formlryctr
     , rcex1p.rxnumber
     , rcex1p.rxnumberql
     , rcex1p.refill
     , rcex1p.dispstatus
     , rcex1p.dtefilled
     , rcex1p.compoundcd
     , rcex1p.prodtypcde
     , rcex1p.productid
     , rcex1p.productkey
     , rcex1p.metricqty
     , rcex1p.decimalqty
     , rcex1p.dayssupply
     , rcex1p.psc
     , rcex1p.writtendte
     , rcex1p.nbrflsauth
     , rcex1p.origincde
     , rcex1p.sbmclarcd1
     , rcex1p.pamcnbr
     , rcex1p.pamccde
     , rcex1p.prauthnbr
     , rcex1p.prauthrsn
     , rcex1p.prauthfdte
     , rcex1p.prauthtdte
     , rcex1p.labelname
     , rcex1p.prodname
     , rcex1p.drugmfgrid
     , rcex1p.drugmfgr
     , rcex1p.gpinumber
     , rcex1p.genericnme
     , rcex1p.prdpacuom
     , rcex1p.prdpacsize
     , rcex1p.ddid
     , rcex1p.gcn
     , rcex1p.gcnseq
     , rcex1p.kdc
     , rcex1p.ahfs
     , rcex1p.drugdeacod
     , rcex1p.rxotcind
     , rcex1p.multsrccde
     , rcex1p.genindover
     , rcex1p.prdreimind
     , rcex1p.brndtrdnme
     , rcex1p.fdatheraeq
     , rcex1p.metricstrg
     , rcex1p.drgstrguom
     , rcex1p.adminroute
     , rcex1p.dosageform
     , rcex1p.mntdrugcde
     , rcex1p.thrdpartyx
     , rcex1p.drgunitdos
     , rcex1p.sbmunitdos
     , rcex1p.altprodtyp
     , rcex1p.altprodcde
     , rcex1p.srxnetwrk
     , rcex1p.srxnettype
     , rcex1p.rxnetwork
     , rcex1p.rxnetwrknm
     , rcex1p.rxnetcarr
     , rcex1p.regioncde
     , rcex1p.phraffil
     , rcex1p.netprior
     , rcex1p.nettype
     , rcex1p.netseq
     , rcex1p.paycntr
     , rcex1p.phrndclst
     , rcex1p.phrgpilst
     , rcex1p.srvprovid
     , rcex1p.srvprovidq
     , rcex1p.npiprov
     , rcex1p.prvncpdpid
     , rcex1p.sbmsrvprid
     , rcex1p.sbmsrvprql
     , rcex1p.srvprovnme
     , rcex1p.provlockql
     , rcex1p.provlockid
     , rcex1p.storenbr
     , rcex1p.affiliatin
     , rcex1p.payeeid
     , rcex1p.disprclass
     , rcex1p.disprother
     , rcex1p.pharmzip
     , rcex1p.presnetwid
     , rcex1p.prescriber
     , rcex1p.prescridql
     , rcex1p.npiprescr
     , rcex1p.prescdeaid
     , rcex1p.preslstnme
     , rcex1p.presfstnme
     , rcex1p.presmdinit
     , rcex1p.presspccde
     , rcex1p.presspccdq
     , rcex1p.fnlplancde
     , rcex1p.fnlplandte
     , rcex1p.planqual
     , rcex1p.plnndclist
     , rcex1p.plngpilist
     , rcex1p.plnpndclst
     , rcex1p.plnpgpilst
     , rcex1p.plandrugst
     , rcex1p.planfrmlry
     , rcex1p.plnfnlpsch
     , rcex1p.phrdcschid
     , rcex1p.phrdcschsq
     , rcex1p.cltdcschid
     , rcex1p.cltdcschsq
     , rcex1p.phrdccscid
     , rcex1p.phrdccscsq
     , rcex1p.cltdccscid
     , rcex1p.cltdccscsq
     , rcex1p.phrprtscid
     , rcex1p.cltprtscid
     , rcex1p.phrrmschid
     , rcex1p.cltrmschid
     , rcex1p.prdpflstid
     , rcex1p.prfprdscid
     , rcex1p.formulary
     , rcex1p.formlrflag
     , rcex1p.tiervalue
     , rcex1p.contherapy
     , rcex1p.message1
     , rcex1p.message2
     , rcex1p.message3
     , rcex1p.rejcnt
     , rcex1p.rejcde1
     , rcex1p.rejcde2
     , rcex1p.rejcde3
     , rcex1p.rjcplanid
     , rcex1p.durconflct
     , rcex1p.durintervn
     , rcex1p.duroutcome
     , rcex1p.lvlservice
     , rcex1p.diagnosis
     , rcex1p.diagnosisq
     , rcex1p.rvdurcnflc
     , rcex1p.rvdurintrv
     , rcex1p.rvduroutcm
     , rcex1p.rvlvlservc
     , rcex1p.drgcnflct1
     , rcex1p.severity1
     , rcex1p.othrpharm1
     , rcex1p.dteprvfil1
     , rcex1p.qtyprvfil1
     , rcex1p.database1
     , rcex1p.othrpresc1
     , rcex1p.freetext1
     , rcex1p.drgcnflct2
     , rcex1p.severity2
     , rcex1p.othrpharm2
     , rcex1p.dteprvfil2
     , rcex1p.qtyprvfil2
     , rcex1p.database2
     , rcex1p.othrpresc2
     , rcex1p.freetext2
     , rcex1p.drgcnflct3
     , rcex1p.severity3
     , rcex1p.othrpharm3
     , rcex1p.dteprvfil3
     , rcex1p.qtyprvfil3
     , rcex1p.database3
     , rcex1p.othrpresc3
     , rcex1p.freetext3
     , rcex1p.feetype
     , rcex1p.awpunitcst
     , rcex1p.wacunitcst
     , rcex1p.geapuntcst
     , rcex1p.ctypeucost
     , rcex1p.basiscost
     , rcex1p.priceqty
     , rcex1p.prodayssup
     , rcex1p.proqty
     , rcex1p.rvincntvsb
     , rcex1p.sbmingrcst
     , rcex1p.sbmdispfee
     , rcex1p.sbmpslstax
     , rcex1p.sbmfslstax
     , rcex1p.sbmslstax
     , rcex1p.sbmpatpay
     , rcex1p.sbmamtdue
     , rcex1p.sbmincentv
     , rcex1p.sbmproffee
     , rcex1p.sbmtothamt
     , rcex1p.sbmopamtct
     , rcex1p.sbmopamtql
     , rcex1p.usualncust
     , rcex1p.denialdte
     , rcex1p.othrpayor
     , rcex1p.calingrcst
     , rcex1p.caldispfee
     , rcex1p.calpstax
     , rcex1p.calfstax
     , rcex1p.calslstax
     , rcex1p.calpatpay
     , rcex1p.caldueamt
     , rcex1p.calwithhld
     , rcex1p.calfcopay
     , rcex1p.calpcopay
     , rcex1p.calcopay
     , rcex1p.calprodsel
     , rcex1p.calatrtax
     , rcex1p.calexcebft
     , rcex1p.calincentv
     , rcex1p.calatrded
     , rcex1p.calcob
     , rcex1p.caltothamt
     , rcex1p.calproffee
     , rcex1p.calothpaya
     , rcex1p.calcostsrc
     , rcex1p.caladmnfee
     , rcex1p.phringrcst
     , rcex1p.phrdispfee
     , rcex1p.phrppstax
     , rcex1p.phrfstax
     , rcex1p.phrslstax
     , rcex1p.phrpatpay
     , rcex1p.phrdueamt
     , rcex1p.phrwithhld
     , rcex1p.phrpprcs
     , rcex1p.phrprcst
     , rcex1p.phrptps
     , rcex1p.unused1
     , rcex1p.phrcopaysc
     , rcex1p.phrcopayss
     , rcex1p.phrfcopay
     , rcex1p.phrpcopay
     , rcex1p.phrcopay
     , rcex1p.phrprodsel
     , rcex1p.phratrtax
     , rcex1p.phrexcebft
     , rcex1p.phrincentv
     , rcex1p.phratrded
     , rcex1p.phrcob
     , rcex1p.phrtothamt
     , rcex1p.phrproffee
     , rcex1p.phrothpaya
     , rcex1p.phrcostsrc
     , rcex1p.phrcosttyp
     , rcex1p.phrprctype
     , rcex1p.phrrate
     , rcex1p.posingrcst
     , rcex1p.posdispfee
     , rcex1p.pospslstax
     , rcex1p.posfslstax
     , rcex1p.posslstax
     , rcex1p.pospatpay
     , rcex1p.posdueamt
     , rcex1p.poswithhld
     , rcex1p.poscopay
     , rcex1p.posprodsel
     , rcex1p.posatrtax
     , rcex1p.posexcebft
     , rcex1p.posincentv
     , rcex1p.posatrded
     , rcex1p.postothamt
     , rcex1p.posproffee
     , rcex1p.posothpaya
     , rcex1p.poscostsrc
     , rcex1p.clientflag
     , rcex1p.cltingrcst
     , rcex1p.cltdispfee
     , rcex1p.cltslstax
     , rcex1p.cltpatpay
     , rcex1p.cltdueamt
     , rcex1p.cltwithhld
     , rcex1p.cltprcs
     , rcex1p.cltprcst
     , rcex1p.cltptps
     , rcex1p.unused2
     , rcex1p.cltcopays
     , rcex1p.cltcopayss
     , rcex1p.cltfcopay
     , rcex1p.cltpcopay
     , rcex1p.cltcopay
     , rcex1p.cltprodsel
     , rcex1p.cltpstax
     , rcex1p.cltfstax
     , rcex1p.cltatrtax
     , rcex1p.cltexcebft
     , rcex1p.cltincentv
     , rcex1p.cltatrded
     , rcex1p.clttothamt
     , rcex1p.cltproffee
     , rcex1p.cltcob
     , rcex1p.cltothpaya
     , rcex1p.cltcostsrc
     , rcex1p.cltcosttyp
     , rcex1p.cltprctype
     , rcex1p.cltrate
     , rcex1p.cltprscstp
     , rcex1p.cltprschnm
     , rcex1p.cltprocfee
     , rcex1p.cltpatstax
     , rcex1p.cltplnstax
     , rcex1p.cltprvnsel
     , rcex1p.cltpscbrnd
     , rcex1p.cltpscnonp
     , rcex1p.cltpscbrnp
     , rcex1p.cltcovgap
     , rcex1p.cltingcstc
     , rcex1p.cltdspfeec
     , rcex1p.rspprocfee
     , rcex1p.rsppatstax
     , rcex1p.rspplnstax
     , rcex1p.rspprvnsel
     , rcex1p.rsppscbrnd
     , rcex1p.rsppscnonp
     , rcex1p.rsppscbrnp
     , rcex1p.rspcovgap
     , rcex1p.rspingcstc
     , rcex1p.rspdspfeec
     , rcex1p.payertype
     , rcex1p.rspreimbur
     , rcex1p.rspingrcst
     , rcex1p.rspdispfee
     , rcex1p.rsppslstax
     , rcex1p.rspfslstax
     , rcex1p.rspslstax
     , rcex1p.rsppatpay
     , rcex1p.rspdueamt
     , rcex1p.rspfcopay
     , rcex1p.rsppcopay
     , rcex1p.rspcopay
     , rcex1p.rspprodsel
     , rcex1p.rspatrtax
     , rcex1p.rspexcebft
     , rcex1p.rspincentv
     , rcex1p.rspatrded
     , rcex1p.rsptothamt
     , rcex1p.rspprofee
     , rcex1p.rspothpaya
     , rcex1p.rspaccuded
     , rcex1p.rsprembft
     , rcex1p.rspremded
     , rcex1p.rspplanid
     , rcex1p.inddedptd
     , rcex1p.inddedrem
     , rcex1p.famdedptd
     , rcex1p.famdedrem
     , rcex1p.dedsched
     , rcex1p.dedaccc
     , rcex1p.dedflag
     , rcex1p.indlbftut
     , rcex1p.indlbftptd
     , rcex1p.indlbftrem
     , rcex1p.famlbftut
     , rcex1p.famlbftptd
     , rcex1p.famlbftrem
     , rcex1p.lftbftmsch
     , rcex1p.lftbftaccc
     , rcex1p.lftbftflag
     , rcex1p.indbftut
     , rcex1p.indbmaxptd
     , rcex1p.fambftut
     , rcex1p.fambmaxptd
     , rcex1p.indbmaxrem
     , rcex1p.fambmaxrem
     , rcex1p.bftmaxschd
     , rcex1p.bftmaxaccc
     , rcex1p.bftmaxflag
     , rcex1p.indoopptd
     , rcex1p.famoopptd
     , rcex1p.indooprem
     , rcex1p.famooprem
     , rcex1p.oopsched
     , rcex1p.oopaccc
     , rcex1p.oopflag
     , rcex1p.contribut
     , rcex1p.contbasis
     , rcex1p.contsched
     , rcex1p.contacccd
     , rcex1p.contflag
     , rcex1p.rxtflag
     , rcex1p.reimbursmt
     , rcex1p.clmorigin
     , rcex1p.hldclmflag
     , rcex1p.hldclmdays
     , rcex1p.partdflag
     , rcex1p.cobextflg
     , rcex1p.paextflg
     , rcex1p.hsaextind
     , rcex1p.ffpmedrmst
     , rcex1p.ffpmedpxst
     , rcex1p.ffpmedmsst
     , rcex1p.incidentid
     , rcex1p.etcnbr
     , rcex1p.dteinjury
     , rcex1p.adduser
     , rcex1p.chguser
     , rcex1p.dmruserid
     , rcex1p.prauserid
     , rcex1p.claimrefid
     , rcex1p.eobdenov
     , rcex1p.eobpdov
     , rcex1p.mantrknbr
     , rcex1p.manrecvdte
     , rcex1p.pasauthtyp
     , rcex1p.pasauthid
     , rcex1p.pasreqtype
     , rcex1p.pasreqfrom
     , rcex1p.pasreqthru
     , rcex1p.pasbasisrq
     , rcex1p.pasrepfn
     , rcex1p.pasrepln
     , rcex1p.passtreet
     , rcex1p.pascity
     , rcex1p.passtate
     , rcex1p.paszip
     , rcex1p.paspanbr
     , rcex1p.pasauthnbr
     , rcex1p.passdocct
     , rcex1p.clientdef1
     , rcex1p.clientdef2
     , rcex1p.clientdef3
     , rcex1p.clientdef4
     , rcex1p.clientdef5
     , rcex1p.cctreserv1
     , rcex1p.cctreserv2
     , rcex1p.cctreserv3
     , rcex1p.cctreserv4
     , rcex1p.cctreserv5
     , rcex1p.cctreserv6
     , rcex1p.cctreserv7
     , rcex1p.cctreserv8
     , rcex1p.cctreserv9
     , rcex1p.cctresrv10
     , rcex1p.cctresrv11
     , rcex1p.cctresrv12
     , rcex1p.cctresrv13
     , rcex1p.cctresrv14
     , rcex1p.userfield
     , rcex1p.messagecd1
     , rcex1p.messagecd2
     , rcex1p.messagecd3
     , rcex1p.extractdte
     , rcex1p.batchctrl
     , rcex1p.clntid
     , rcex1p.clntsgmnt
     , rcex1p.clntregion
     , rcex1p.pprstate
     , rcex1p.sbmplsrvce
     , rcex1p.sbmpatresd
     , rcex1p.chgdate
     , rcex1p.chgtime
     , rcex1p.sbmcmpdtyp
     , rcex1p.sbmclarcd2
     , rcex1p.sbmclarcd3
     , rcex1p.adminrtesn
     , rcex1p.nda
     , rcex1p.anda
     , rcex1p.andaor
     , rcex1p.rxnormcode
     , rcex1p.mntsource
     , rcex1p.mntcarpror
     , rcex1p.mntgpilist
     , rcex1p.cpqspcprg
     , rcex1p.cpqspcpgin
     , rcex1p.cpqspcschd
     , rcex1p.rxnetwrkql
     , rcex1p.rxnetprcql
     , rcex1p.prsstate
     , rcex1p.sbmrphid
     , rcex1p.sbmrphidql
     , rcex1p.plantype
     , rcex1p.lstqualndc
     , rcex1p.lstqualgpi
     , rcex1p.ctschedid
     , rcex1p.prbasischd
     , rcex1p.regdisor
     , rcex1p.drugststbl
     , rcex1p.transben
     , rcex1p.pharsrvtyp
     , rcex1p.benunitcst
     , rcex1p.sbmmdpdamt
     , rcex1p.calprocfee
     , rcex1p.calpatstax
     , rcex1p.calplnstax
     , rcex1p.calprvnsel
     , rcex1p.calpscbrnd
     , rcex1p.calpscnonp
     , rcex1p.calpscbrnp
     , rcex1p.calcovgap
     , rcex1p.calingcstc
     , rcex1p.caldspfeec
     , rcex1p.phrprocfee
     , rcex1p.phrpatstax
     , rcex1p.phrplnstax
     , rcex1p.phrprvnsel
     , rcex1p.phrpscbrnd
     , rcex1p.phrpscnonp
     , rcex1p.phrpscbrnp
     , rcex1p.phrcovgap
     , rcex1p.phringcstc
     , rcex1p.phrdspfeec
     , rcex1p.posprocfee
     , rcex1p.pospatstax
     , rcex1p.posplnstax
     , rcex1p.posprvnsel
     , rcex1p.pospscbrnd
     , rcex1p.pospscnonp
     , rcex1p.pospscbrnp
     , rcex1p.poscovgap
     , rcex1p.posingcstc
     , rcex1p.posdspfeec
     , rcex1p.cltptpst
     , rcex1p.phrptpst
     , rcex1p.benstgql1
     , rcex1p.benstgamt1
     , rcex1p.benstgql2
     , rcex1p.benstgamt2
     , rcex1p.benstgql3
     , rcex1p.benstgamt3
     , rcex1p.benstgql4
     , rcex1p.benstgamt4
     , rcex1p.estgensav
     , rcex1p.spdacctrem
     , rcex1p.hlthplnamt
     , rcex1p.delayrsncd
     , rcex1p.medcdind
     , rcex1p.medcdid
     , rcex1p.medcdagnbr
     , rcex1p.medcdtcn
     , rcex1p.fmstier
     , rcex1p.fmsstatus
     , rcex1p.fmsdfltind
     , rcex1p.fmsbenlst
     , rcex1p.fmslstlvl3
     , rcex1p.fmslstlvl2
     , rcex1p.fmslstlvl1
     , rcex1p.fmsruleset
     , rcex1p.fmsrule
     , rcex1p.fmsproccd
  FROM dwxtracth.NAE2202XT  rcex1p;

