DROP TABLE ${STAGING_SCHEMA}.D_SUPER_NTWK_NDC_GPI_i;

CREATE TABLE ${STAGING_SCHEMA}.D_SUPER_NTWK_NDC_GPI_i
( SUPER_NW_NDC_GPI_SK           BIGINT NOT NULL
, SNH_SUPER_NW_ID               CHARACTER VARYING(6)
, SNH_SEQ_NBR                   INTEGER
, SUPER_NW_NDC_GPI_CD           CHARACTER VARYING(10)
, SUPER_NW_NDC_GPI_TYP          CHARACTER VARYING(2)
, SN1_SEQ                       INTEGER
, SUPER_NW_NDC_GPI_QL           CHARACTER(1)
, PHR_PRICE_SCHEDULE            CHARACTER VARYING(10)
, PHR_PATIENT_PAY               CHARACTER VARYING(10)
, CLT_PRICE_SCHEDULE            CHARACTER VARYING(10)
, CLT_PATIENT_PAY               CHARACTER VARYING(10)
, PRICE_BASIS_SCHEDULE          CHARACTER VARYING(10)
, SN1_MSG_CD                    CHARACTER VARYING(10)
, SN1_MSG_TYPE                  CHARACTER(1)
, SN1_DEDUCTIBLE                CHARACTER VARYING(10)
, SN1_DEDUCTIBLE_ACCUM_CODE     CHARACTER VARYING(10)
, SN1_OUT_OF_POCKET             CHARACTER VARYING(10)
, SN1_OOP_ACCUM_CODE            CHARACTER VARYING(10)
, SN1_BENEFIT_MAX               CHARACTER VARYING(10)
, SN1_BEN_MAX_ACCUM_CODE        CHARACTER VARYING(10)
, SN1_LIFETIME_BENEFIT_MAX      CHARACTER VARYING(10)
, SN1_LIFETIME_BEN_MAX_ACCUM    CHARACTER VARYING(10)
, SN1_FROM_DT                   DATE
, SN1_THRU_DT                   DATE
, SN1_STS                       CHARACTER(1)
, SN1_PHR_PROF_SRV_FEE_TBL      CHARACTER VARYING(10)
, SN1_CLT_PROF_SRV_FEE_TBL      CHARACTER VARYING(10)
, SN1_SPREAD_PRICING_FLG        CHARACTER(1)
, SN1_PHARM_DUR_PPS_FEE         CHARACTER VARYING(10)
, SN1_CLT_DUR_PPS_FEE           CHARACTER VARYING(10)
, SN1_CLT_2_PRICE_SCHED         CHARACTER VARYING(10)
, SN1_CLT_3_PRICE_SCHED         CHARACTER VARYING(10)
, SN1_CLT_PATPAY_GRP_SCHID      CHARACTER VARYING(10)
, SN1_CLT1_PRCE_GRP_SCHID       CHARACTER VARYING(10)
, SN1_CLT2_PRCE_GRP_SCHID       CHARACTER VARYING(10)
, SN1_CLT3_PRCE_GRP_SCHID       CHARACTER VARYING(10)
, SN1_PHR_PAT_PAY_GRP_SCHID     CHARACTER VARYING(10)
, SN1_PHR_PRICE_GRP_SCHID       CHARACTER VARYING(10)
, SN1_USER_SEQ_NBR              INTEGER
, SN1_QLFR_TYPE_SEQ             INTEGER
, SRC_ENV_SK                    BIGINT NOT NULL
, INSERT_TS                     TIMESTAMP NOT NULL
, UPDATE_TS                     TIMESTAMP NOT NULL
, INSERT_UID                    CHARACTER VARYING(20)
, UPDATE_UID                    CHARACTER VARYING(20)
, RUN_ID                        BIGINT
, REC_STAT_CD                   BYTEINT
);
