DROP TABLE ${STAGING_SCHEMA}.d_pharmacy_relationship_u;

CREATE TABLE ${STAGING_SCHEMA}.d_pharmacy_relationship_u
( phr_relshp_sk                    BIGINT
, phr_sk                           BIGINT
, phr_afflt_sk                     BIGINT
, phr_pmt_cntr_sk                  BIGINT
, phr_id                           VARCHAR(12)
, phr_relshp_seq_no                INTEGER
, phr_affl_cd                      VARCHAR(6)
, phr_pmt_cntr_id                  VARCHAR(12)
, phr_relshp_stat_cd               CHAR(1)
, phr_relshp_eff_dt                DATE
, phr_relshp_thru_dt               DATE
, phr_relshp_cd                    VARCHAR(6)
, phr_relshp_typ_cd                VARCHAR(2)
, phr_relshp_nm                    VARCHAR(35)
, phr_relshp_addr1_txt             VARCHAR(55)
, phr_relshp_addr2_txt             VARCHAR(55)
, phr_relshp_city_nm               VARCHAR(30)
, phr_relshp_st_cd                 VARCHAR(2)
, phr_relshp_zip_cd                VARCHAR(15)
, phr_relshp_zip2_cd               VARCHAR(4)
, phr_relshp_zip3_cd               VARCHAR(2)
, phr_relshp_cntry_cd              VARCHAR(4)
, phr_relshp_mail_addr1_txt        VARCHAR(55)
, phr_relshp_mail_addr2_txt        VARCHAR(55)
, phr_relshp_mail_city_nm          VARCHAR(30)
, phr_relshp_mail_st_cd            VARCHAR(2)
, phr_relshp_mail_zip1_cd          VARCHAR(5)
, phr_relshp_mail_zip2_cd          VARCHAR(4)
, phr_relshp_mail_zip3_cd          VARCHAR(2)
, phr_relshp_mail_cntry_cd         VARCHAR(4)
, phr_relshp_cntct_nm              VARCHAR(40)
, phr_relshp_cntct_title_nm        VARCHAR(30)
, phr_relshp_phone_no              BIGINT
, phr_relshp_phone_ext_no          BIGINT
, phr_relshp_fax_phone             BIGINT
, phr_relshp_cntct_email_txt       VARCHAR(80)
, phr_affl_stat_cd                 CHAR(1)
, phr_relshp_obsolete_dt           DATE
, phr_relshp_parent_org_id         VARCHAR(30)
, src_env_sk                       BIGINT
, insert_ts                        TIMESTAMP
, update_ts                        TIMESTAMP
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
);

