DROP TABLE ${STAGING_SCHEMA}.f_mpd_pde_history_u;

CREATE TABLE ${STAGING_SCHEMA}.f_mpd_pde_history_u
( cms_pharmacy_cost_sk             BIGINT
, cms_drug_pricing_file_sk         BIGINT
, cms_stars_calendar_submission_sk BIGINT
, cms_proxy_ndc_rxcui_sk           BIGINT
, prod_sk                          BIGINT
, cag_sk                           BIGINT
, mbr_sk                           BIGINT
, pde_claim_nbr                    BIGINT
, pde_claim_seq_nbr_src            BIGINT
, pde_claim_stat_id                CHAR(1)
, pde_contract_id                  VARCHAR(5)
, pde_pbp_id                       VARCHAR(3)
, pde_carrier_id                   VARCHAR(9)
, pde_final_pln_cd                 VARCHAR(10)
, pde_proxy_prod_id                VARCHAR(20)
, pde_proxy_ndc_label_nm           VARCHAR(100)
, pde_prod_id                      VARCHAR(20)
, pde_ndc_label_nm                 VARCHAR(100)
, pde_brand_generic_cd             CHAR(1)
, pde_phr_id                       VARCHAR(15)
, pde_phr_npi_id                   VARCHAR(10)
, pde_phr_svc_typ                  VARCHAR(2)
, pde_residence_cd                 VARCHAR(2)
, pde_residence_cd_desc            VARCHAR(100)
, pde_filled_dt                    DATE
, pde_file_sbm_ts                  TIMESTAMP
, pde_file_proc_ts                 TIMESTAMP
, pde_drg_qty                      DECIMAL(11,3)
, pde_days_of_supply               SMALLINT
, mpf_days_of_supply               SMALLINT
, pde_ndc_cost                     DECIMAL(13,2)
, pde_ndc_unit_cost                DECIMAL(13,5)
, mpf_ndc_unit_cost                DECIMAL(13,4)
, pde_dispensing_fee               DECIMAL(9,2)
, phr_cost_type                    VARCHAR(10)
, cur_claim_stat_id                CHAR(1)
, pl_of_svc_submd                  VARCHAR(2)
, cms_stat_id                      CHAR(1)
, pde_ndc_uom                      VARCHAR(2)
, proxy_ndc_uom                    VARCHAR(2)
, pde_ndc_inactive_dt              DATE
, pde_ndc_obsolete_dt              DATE
, pde_adj_del_cd                   CHAR(1)
, price_id                         VARCHAR(3)
, mpf_dispensing_fee               DECIMAL(13,4)
, tot_pde_drug_cost                DECIMAL(15,2)
, tot_mpf_drug_cost                DECIMAL(15,4)
, tot_est_pde_cost                 DECIMAL(15,2)
, tot_est_mpf_cost                 DECIMAL(15,4)
, tot_est_discrepancy              DECIMAL(15,4)
, cms_segment_id                   CHAR(3)
, cal_start_dt                     DATE
, cal_end_dt                       DATE
, pricing_file_mail_flg            CHAR(1)
, preferred_status_mail_flg        CHAR(1)
, phr_retail_flg                   CHAR(1)
, phr_mail_flg                     CHAR(1)
, phr_la_drugs_flg                 CHAR(1)
, phr_hi_flg                       CHAR(1)
, phr_ltc_flg                      CHAR(1)
, preferred_status_retail_flg      CHAR(1)
, prod_directory_dt                DATE
, claim_phr_sk                     BIGINT
, pde_record_id                    VARCHAR(3)
, pde_gpi_id                       VARCHAR(14)
, floor_price                      DECIMAL(15,4)
, pde_file_id                      VARCHAR(10)
, pde_medicare_id                  VARCHAR(20)
, pde_paid_dt                      DATE
, pde_refill_nbr                   VARCHAR(2)
, pde_dispns_stat                  CHAR(1)
, pde_compound_cd                  CHAR(1)
, pde_pbr_id                       VARCHAR(15)
, pde_drg_cvg_cd                   CHAR(1)
, pde_non_stnd_cd                  CHAR(1)
, price_exceptn_cd                 CHAR(1)
, catast_cvg_cd                    CHAR(1)
, pde_gdcb_amt                     DECIMAL(9,2)
, pde_gdca_amt                     DECIMAL(9,2)
, pde_pat_pay_amt                  DECIMAL(9,2)
, pde_othr_troop_amt               DECIMAL(9,2)
, pde_lics_amt                     DECIMAL(9,2)
, pde_plro_amt                     DECIMAL(9,2)
, pde_cpp_amt                      DECIMAL(9,2)
, pde_npp_amt                      DECIMAL(9,2)
, pde_est_rbt_amt                  DECIMAL(9,2)
, pde_vaccn_fee                    DECIMAL(9,2)
, pde_rx_org_cd                    CHAR(1)
, pde_tot_drg_grs_cost             DECIMAL(9,2)
, pde_true_troop_accom             DECIMAL(9,2)
, pde_ben_phs_begn                 CHAR(1)
, pde_ben_phs_end                  CHAR(1)
, pde_gap_discnt_amt               DECIMAL(9,2)
, pde_drug_tier                    CHAR(1)
, pde_adj_rsn_cd                   VARCHAR(12)
, cms_cal_gap_dscnt_amt            DECIMAL(9,2)
, pde_edit_cnt                     SMALLINT
, pde_edit_cd_1                    VARCHAR(3)
, pde_edit_cd_2                    VARCHAR(3)
, pde_edit_cd_3                    VARCHAR(3)
, pde_edit_cd_4                    VARCHAR(3)
, pde_edit_cd_5                    VARCHAR(3)
, pde_edit_cd_6                    VARCHAR(3)
, pde_edit_cd_7                    VARCHAR(3)
, pde_edit_cd_8                    VARCHAR(3)
, pde_edit_cd_9                    VARCHAR(3)
, pde_edit_cd_10                   VARCHAR(3)
, pde_mbr_id                       VARCHAR(18)
, pde_account_id                   VARCHAR(15)
, pde_group_id                     VARCHAR(15)
, pde_resbm_cms_type               CHAR(1)
, pde_clm_rcvd_dt                  DATE
, final_pln_eff_dt                 DATE
, pbp_of_record                    VARCHAR(3)
, alt_srv_provider_qual            VARCHAR(2)
, alt_srv_provider_id              VARCHAR(15)
, orig_sbm_contract_id             VARCHAR(5)
, contract_of_record               VARCHAR(5)
, sales_tax                        DECIMAL(9,2)
, adj_begin_ts                     TIMESTAMP
, pde_formulary_cd                 CHAR(1)
, gap_discnt_pln_ovcd              CHAR(1)
, trans_rpt_sts_uid                VARCHAR(10)
, pde_resbm_uid                    VARCHAR(10)
, pde_reproces_uid                 VARCHAR(10)
, mdd_seq_nbr                      BIGINT
, pde_exclution_rsn_cd             VARCHAR(3)
, sbm_prescriber_qual              VARCHAR(2)
, sbm_prod_select_cd               CHAR(1)
, sbm_clarification_cd             VARCHAR(2)
, pde_resubmission_stat            CHAR(1)
, pde_reproc_file_id               VARCHAR(10)
, pde_reproc_sbmtr_id              VARCHAR(6)
, sbm_srv_provider_qual            VARCHAR(2)
, corrected_medicare_id            VARCHAR(20)
, sbm_rx_nbr                       VARCHAR(12)
, pde_trans_rpt_sts_ts             TIMESTAMP
, pde_resbm_sts_ts                 TIMESTAMP
, pde_reproc_ts                    TIMESTAMP
, pde_adj_rsn_cd_qual              CHAR(1)
, pde_sbmtr_id                     VARCHAR(6)
, pde_file_from_dt                 DATE
, pde_file_thru_dt                 DATE
, pde_file_type                    CHAR(1)
, pde_clnt_lst_nm                  VARCHAR(10)
, pde_version                      CHAR(1)
, mdd_fill_type                    CHAR(1)
, mdd_add_user_id                  VARCHAR(10)
, mdd_add_ts                       TIMESTAMP
, mdd_add_pgm                      VARCHAR(10)
, mdd_chg_user_id                  VARCHAR(10)
, mdd_chg_ts                       TIMESTAMP
, mdd_chg_pgm                      VARCHAR(10)
, mdh_det_rcd_count                BIGINT
, mdh_det_rcd_accpt                BIGINT
, mdh_det_rcd_infml                BIGINT
, mdh_det_rcd_rejct                BIGINT
, mdh_file_trns_dt                 DATE
, mdh_add_user_id                  VARCHAR(10)
, mdh_add_ts                       TIMESTAMP
, mdh_add_pgm                      VARCHAR(10)
, mdh_chg_user_id                  VARCHAR(10)
, mdh_chg_ts                       TIMESTAMP
, mdh_chg_pgm                      VARCHAR(10)
, src_env_sk                       BIGINT NOT NULL
, insert_ts                        TIMESTAMP NOT NULL
, update_ts                        TIMESTAMP NOT NULL
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
)
DISTRIBUTE ON (MBR_SK);

