DROP TABLE ${STAGING_SCHEMA}.f_claim_txn_omn_extn_i;

CREATE TABLE ${STAGING_SCHEMA}.f_claim_txn_omn_extn_i
( claim_nbr                        BIGINT
, claim_seq_nbr                    INTEGER
, claim_stat_id                    CHAR(1)
, carrier_sk                       BIGINT
, cag_sk                           BIGINT
, mbr_sk                           BIGINT
, sbm_dt                           DATE
, sbm_dt_sk                        BIGINT
, filled_dt                        DATE
, filled_dt_sk                     BIGINT
, hdr_wrapper                      VARCHAR(32)
, invtry_catgy_cd                  VARCHAR(8)
, ptnt_id                          VARCHAR(10)
, pbr_dea_id                       VARCHAR(15)
, pay_plan_typ                     CHAR(1)
, bt_id                            VARCHAR(11)
, btp_id                           BIGINT
, payr_seq_cd                      CHAR(1)
, orig_wrtn_ndc                    VARCHAR(11)
, subst_typ                        CHAR(1)
, actul_acqstion_cost              DECIMAL(11,5)
, disp_typ                         CHAR(1)
, comp_nbr                         VARCHAR(10)
, written_dt_sk                    BIGINT
, cost_basis                       CHAR(2)
, pmt_typ                          CHAR(1)
, pay_plan                         VARCHAR(10)
, ptnt_loc_cd                      CHAR(2)
, orig_of_rx_cd                    CHAR(1)
, claim_ind                        CHAR(1)
, chain_cd                         CHAR(1)
, diag_cd                          VARCHAR(10)
, facility                         VARCHAR(10)
, return_typ                       CHAR(1)
, prn_ind                          CHAR(1)
, additional_fld_3                 CHAR(1)
, additional_fld_4                 CHAR(1)
, nabp_nbr                         VARCHAR(7)
, dose_freq                        DECIMAL(7,2)
, dose_qty                         DECIMAL(7,2)
, filler                           VARCHAR(6)
, orig_sbm_bin                     VARCHAR(6)
, orig_sbm_pcn                     VARCHAR(10)
, orig_prescbd_qty                 DECIMAL(10,3)
, client_defind_fld_1              VARCHAR(10)
, client_defind_fld_2              VARCHAR(10)
, client_defind_fld_3              VARCHAR(10)
, client_defind_fld_4              VARCHAR(10)
, client_defind_fld_5              VARCHAR(10)
, client_defind_fld_6              VARCHAR(10)
, client_defind_fld_7              VARCHAR(10)
, client_defind_fld_8              VARCHAR(10)
, client_defind_fld_9              VARCHAR(10)
, client_defind_fld_10             VARCHAR(10)
, elig_clarif_cd                   CHAR(1)
, prscrptn_orig_cd                 CHAR(1)
, srvc_level                       CHAR(2)
, orif_cust_loc_cd                 CHAR(2)
, filler_2                         VARCHAR(100)
, src_env_sk                       BIGINT
, insert_ts                        TIMESTAMP
, update_ts                        TIMESTAMP
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
)
DISTRIBUTE ON (MBR_SK);

