DROP TABLE ${STAGING_SCHEMA}.d_plan_ndc_i;

CREATE TABLE ${STAGING_SCHEMA}.d_plan_ndc_i
( plan_ndc_sk                      BIGINT NOT NULL
, ndc_lst_nm                       CHAR(6)
, ndc_labeler_cd                   CHAR(5)
, ndc_prod_cd                      CHAR(4)
, ndc_pkg_cd                       CHAR(2)
, label_nm                         CHAR(25)
, curr_dt_effec                    DATE
, curr_dt_termed                   DATE
, curr_drg_stat                    CHAR(1)
, prev_eft_dt                      DATE
, prev_thru_dt                     DATE
, prev_drg_stat                    CHAR(1)
, program_nm                       CHAR(10)
, qty_min                          DECIMAL(11,3)
, qty_max                          DECIMAL(11,3)
, days_supply_min                  INTEGER
, days_supply_max                  INTEGER
, qty_ds_comp_max                  CHAR(1)
, period_qty_typ                   CHAR(1)
, period_qty_days                  INTEGER
, period_qty_max                   DECIMAL(11,3)
, period_ds_type                   CHAR(1)
, period_ds_days                   INTEGER
, period_ds_max                    INTEGER
, period_qty_compmax               CHAR(1)
, period_fills_type                CHAR(1)
, period_fills_days                INTEGER
, period_fills_max                 INTEGER
, refill_limits_max_nbr            INTEGER
, refill_expire_after_days         INTEGER
, amt_due_type                     CHAR(1)
, amt_due_days                     INTEGER
, amt_due_max                      DECIMAL(10,2)
, amt_due_basis                    CHAR(1)
, patient_age_min                  INTEGER
, patient_age_max                  INTEGER
, patient_age_qlfr                 CHAR(1)
, patient_age_wkday                CHAR(1)
, daily_dose_min                   DECIMAL(11,6)
, daily_dose_max                   DECIMAL(11,6)
, acute_dosing_days_max            INTEGER
, maint_dosing_day_max             INTEGER
, package_size_comp_cde            CHAR(1)
, otc_ovrd                         CHAR(1)
, unit_dose                        CHAR(1)
, fda_therapeutic_equiv            CHAR(1)
, route_of_administratn            CHAR(1)
, maintenance_drg_sts              CHAR(1)
, brand_genric_edit                CHAR(1)
, state_list_nm                    CHAR(10)
, gpi_list_edit                    CHAR(1)
, sex_exclusion                    CHAR(1)
, slt_specialty_list_cd            CHAR(6)
, dgl_diagnosis_list               CHAR(6)
, md_ntwk_id                       CHAR(6)
, phn_phr_ntwk_id                  CHAR(6)
, phn_seq_nbr                      INTEGER
, fmly_coverage                    CHAR(1)
, dependant_age_min                INTEGER
, dependant_age_max                INTEGER
, pref_prod_ndc_labeler            CHAR(5)
, pref_prod_ndc_prod               CHAR(4)
, pref_prod_ndc_package            CHAR(2)
, form_alt_ndc_labeler             CHAR(5)
, form_alt_ndc_prod                CHAR(4)
, form_alt_ndc_package             CHAR(2)
, message_cd                       CHAR(10)
, message_type                     CHAR(1)
, md_ntwk_qlfr                     CHAR(1)
, prf_pbr_id                       CHAR(15)
, prq_pbr_id_qlfr                  CHAR(2)
, prf_pbr_id_state                 CHAR(3)
, pbr_ovrd                         CHAR(1)
, phr_ntwk_qual                    CHAR(1)
, pha_phr_id                       CHAR(12)
, phr_ovrd                         CHAR(1)
, ptd_frm_dt                       DATE
, daily_dose_ql                    CHAR(1)
, diagnosis_list_qual              CHAR(1)
, specl_list_qlfr                  CHAR(1)
, limit_days                       INTEGER
, refill_cd                        CHAR(2)
, days_supply_filllimit            INTEGER
, fills_in_hx_filllimit            INTEGER
, suppress_dea_edit                CHAR(1)
, use_benefit_reset                CHAR(1)
, md_ntwk_drg_sts                  CHAR(1)
, specl_list_drg_sts               CHAR(1)
, fill_ovrd_multi_src              CHAR(1)
, fill_ovrd_prod                   CHAR(1)
, ovrde_medicaid_prod              CHAR(1)
, other_fam_mbr_cov_sts            CHAR(1)
, tbs_trans_ben_ovrd_scde          CHAR(10)
, period_to_dt_qtylvl              CHAR(1)
, period_to_dt_ds_lvl              CHAR(1)
, period_to_dt_fillvl              CHAR(1)
, pno_desi                         CHAR(1)
, payer_type                       CHAR(1)
, fda_non_approval                 CHAR(1)
, period_psq_type                  CHAR(1)
, period_psq_days                  INTEGER
, period_psq_max                   DECIMAL(11,3)
, period_to_dt_psqlvl              CHAR(1)
, super_ntwk_id                    CHAR(6)
, snh_seq_nbr                      INTEGER
, super_ntwk_qual                  CHAR(1)
, period_fills_max_qty             DECIMAL(11,3)
, patient_age_proc_qual            CHAR(1)
, patient_age_max_unit             CHAR(1)
, patient_age_min_unit             CHAR(1)
, dx_list_drg_stat                 CHAR(1)
, therapeutic_class                CHAR(1)
, fml_form_alt_list_nm             CHAR(10)
, form_alt_saving                  CHAR(1)
, form_alt_saving_amt              DECIMAL(6,2)
, reject_interval                  INTEGER
, reject_interval_type             CHAR(1)
, reject_interval_days             INTEGER
, ris_rej_interval_sch_id          CHAR(10)
, isc_incentive_sched_id           CHAR(10)
, rtx_taxonomy_list_id             CHAR(6)
, taxonomy_list_qual               CHAR(1)
, taxonomy_lst_drg_sts             CHAR(1)
, tb_ovrd_flag                     CHAR(1)
, ptd_src                          CHAR(1)
, ptd_eff_frm                      DATE
, reject_cd_remap_tbl              CHAR(10)
, refill_limits                    INTEGER
, worker_comp_state_lst            CHAR(10)
, injury_frm_dt                    DATE
, injury_thru_dt                   DATE
, phr_service_typ                  CHAR(10)
, phr_ser_typ_qual                 CHAR(1)
, phr_ser_typ_drg_sts              CHAR(1)
, fxd_dte_of_injury_qul            CHAR(1)
, fxd_dte_of_injury                DATE
, ptd_frm_source                   CHAR(1)
, workers_comp_ql                  CHAR(1)
, add_dt                           DATE
, chg_dt                           DATE
, src_env_sk                       BIGINT NOT NULL
, insert_ts                        TIMESTAMP NOT NULL
, update_ts                        TIMESTAMP NOT NULL
, insert_uid                       CHAR(20)
, update_uid                       CHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
);

