DROP TABLE ${STAGING_SCHEMA}.f_formulary_claim_trx_u;

CREATE TABLE ${STAGING_SCHEMA}.f_formulary_claim_trx_u
( claim_nbr                        BIGINT
, claim_seq_nbr                    INTEGER
, claim_stat_id                    CHAR(1)
, carrier_id                       VARCHAR(30)
, account_id                       VARCHAR(40)
, employer_group_id                VARCHAR(30)
, mbr_id                           VARCHAR(20)
, cag_sk                           BIGINT
, mbr_sk                           BIGINT
, sbm_dt                           VARCHAR(8)
, sbm_dt_sk                        BIGINT
, subm_yr                          INTEGER
, subm_mnth                        INTEGER
, subm_yr_mnth                     INTEGER
, filled_dt                        DATE
, filled_dt_sk                     BIGINT
, filled_yr                        INTEGER
, filled_mnth                      INTEGER
, filled_yr_mnth                   INTEGER
, cust_id                          VARCHAR(10)
, bnft_lst_id                      VARCHAR(10)
, tier                             INTEGER
, frmulry_sts                      INTEGER
, dflt_used                        CHAR(1)
, multi_ingrdnt_sts                CHAR(1)
, formulary_list_id                INTEGER
, rule_set_id                      INTEGER
, rule_id                          INTEGER
, ovrd_tier                        VARCHAR(2)
, ovrd_formulary_sts               VARCHAR(2)
, msg_cd                           VARCHAR(10)
, msg_type                         CHAR(1)
, crit_sche                        VARCHAR(10)
, crit_sched                       VARCHAR(3)
, crit_msg_cd                      VARCHAR(10)
, crit_msg_typ                     CHAR(1)
, crit_drg_sts                     CHAR(1)
, fsl_rule_set_id                  VARCHAR(10)
, fsl_rule_id                      VARCHAR(10)
, splty_pgm_ind                    CHAR(1)
, thrpc_area                       VARCHAR(2)
, prod_pricing                     VARCHAR(2)
, frl_rule_set_id                  VARCHAR(10)
, frl_rule_id                      VARCHAR(10)
, pa_required                      CHAR(1)
, medical_necessity                CHAR(1)
, step_thrpy_required              CHAR(1)
, prod_exclusion                   CHAR(1)
, pa_typ                           CHAR(1)
, step_thrpy_typ                   CHAR(1)
, step_thrpy_nbr                   INTEGER
, fpl_rule_set_id                  VARCHAR(10)
, fpl_rule_id                      VARCHAR(10)
, qty_lmts                         CHAR(1)
, max_amt_qlfr                     VARCHAR(2)
, max_amt                          DECIMAL(10,3)
, max_amt_time_perd                VARCHAR(2)
, max_amt_time_unts                INTEGER
, max_amt_time_strt                DATE
, max_amt_time_end                 DATE
, gndr_cd                          CHAR(1)
, min_age                          INTEGER
, min_age_qlfr                     CHAR(1)
, max_age                          INTEGER
, max_age_qlfr                     CHAR(1)
, fal_rule_set_id                  VARCHAR(10)
, fal_rule_id                      VARCHAR(10)
, prod_id                          VARCHAR(20)
, prod_id_qlfr                     VARCHAR(2)
, prod_sk                          BIGINT
, alt_prod_seq1                    VARCHAR(2)
, alt_prod_typ1                    CHAR(1)
, alt_prod_id1                     VARCHAR(70)
, alt_prod_seq2                    VARCHAR(2)
, alt_prod_typ2                    CHAR(1)
, alt_prod_id2                     VARCHAR(70)
, alt_prod_seq3                    VARCHAR(2)
, alt_prod_typ3                    CHAR(1)
, alt_prod_id3                     VARCHAR(70)
, alt_prod_seq4                    VARCHAR(2)
, alt_prod_typ4                    CHAR(1)
, alt_prod_id4                     VARCHAR(70)
, alt_prod_seq5                    VARCHAR(2)
, alt_prod_typ5                    CHAR(1)
, alt_prod_id5                     VARCHAR(70)
, alt_prod_seq6                    VARCHAR(2)
, alt_prod_typ6                    CHAR(1)
, alt_prod_id6                     VARCHAR(70)
, alt_prod_seq7                    VARCHAR(2)
, alt_prod_typ7                    CHAR(1)
, alt_prod_id7                     VARCHAR(70)
, alt_prod_seq8                    VARCHAR(2)
, alt_prod_typ8                    CHAR(1)
, alt_prod_id8                     VARCHAR(70)
, reserved_fld1                    VARCHAR(20)
, reserved_fld2                    VARCHAR(20)
, reserved_fld3                    VARCHAR(20)
, reserved_fld4                    VARCHAR(20)
, reserved_fld5                    VARCHAR(20)
, reserved_fld6                    VARCHAR(20)
, reserved_fld7                    VARCHAR(20)
, reserved_fld8                    VARCHAR(20)
, reserved_fld9                    VARCHAR(20)
, reserved_fld10                   VARCHAR(20)
, reserved_fld11                   VARCHAR(20)
, reserved_fld12                   VARCHAR(20)
, reserved_fld13                   VARCHAR(20)
, reserved_fld14                   VARCHAR(20)
, reserved_fld15                   VARCHAR(20)
, src_env_sk                       BIGINT NOT NULL
, insert_ts                        TIMESTAMP NOT NULL
, update_ts                        TIMESTAMP NOT NULL
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
);

