DROP TABLE ${STAGING_SCHEMA}.f_audit_note_mthly_clms_detail_i;

CREATE TABLE ${STAGING_SCHEMA}.f_audit_note_mthly_clms_detail_i
( submd_mnth_id                    INTEGER
, claim_nbr                        BIGINT
, mbr_sk                           BIGINT
, cag_sk                           BIGINT
, phr_sk                           BIGINT
, audit_category_sk                BIGINT
, audit_payment_type_sk            BIGINT
, audit_job_sk                     BIGINT
, audit_type_sk                    BIGINT
, audit_fraud_type_sk              BIGINT
, audit_violation_reason_sk        BIGINT
, audit_fraud_violation_reason_sk  BIGINT
, audit_fraud_perpetrator_sk       BIGINT
, audit_nonfraud_violation_reason_sk BIGINT
, pbr_sk                           BIGINT
, prod_sk                          BIGINT
, compound_sk                      BIGINT
, claim_seq_nbr                    INTEGER
, claim_stat_id                    CHAR(1)
, sbm_dt                           DATE
, carrier_id                       VARCHAR(30)
, account_id                       VARCHAR(40)
, employer_group_id                VARCHAR(30)
, mbr_id                           VARCHAR(20)
, rx_nbr                           VARCHAR(12)
, audit_src_data                   CHAR(1)
, phr_ncpdp_id                     VARCHAR(12)
, phr_npi_no                       VARCHAR(12)
, phr_st_cd                        VARCHAR(3)
, phr_st_desc                      VARCHAR(50)
, pbr_npi_id                       VARCHAR(10)
, pbr_dea_id                       VARCHAR(15)
, pbr_st_cd                        VARCHAR(3)
, filled_dt                        DATE
, rx_written_dt                    DATE
, days_sply                        SMALLINT
, drg_qty                          DECIMAL(11,3)
, drg_ndc_id                       VARCHAR(20)
, drg_ndc_short_id                 VARCHAR(9)
, drg_lbl_nm                       VARCHAR(30)
, compound_cd                      CHAR(1)
, compound_cd_desc                 VARCHAR(50)
, cms_contract_id                  VARCHAR(5)
, cms_pbp_id                       VARCHAR(3)
, app_due_amt                      DECIMAL(9,2)
, auditior_id                      VARCHAR(30)
, audit_call_note_id               INTEGER
, call_note_entry_dt               TIMESTAMP
, phr_adjust_amt                   DECIMAL(20,3)
, audit_category_id                INTEGER
, zero_reclaim                     CHAR(1)
, audit_payment_type_id            INTEGER
, phr_contact_nm                   VARCHAR(50)
, number_of_calls                  INTEGER
, number_of_emails                 INTEGER
, audit_type_id                    INTEGER
, audit_fraud_type_id              INTEGER
, audit_violation_reason_id        INTEGER
, audit_fraud_violation_reason_id  INTEGER
, audit_fraud_perpetrator_id       INTEGER
, audit_nonfraud_violation_reason_id INTEGER
, comments                         VARCHAR(155)
, src_created_dt                   TIMESTAMP
, src_created_by                   VARCHAR(30)
, src_insert_dt                    TIMESTAMP
, src_update_ts                    TIMESTAMP
, src_env_sk                       BIGINT NOT NULL
, insert_ts                        TIMESTAMP NOT NULL
, update_ts                        TIMESTAMP NOT NULL
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
, clt_due_amt                      DECIMAL(9,2)
, clt_adjust_amt                   DECIMAL(20,3)
, phr_adjust_cal_amt               DECIMAL(20,3)
, clt_adjust_cal_amt               DECIMAL(20,3)
, sbm_tm                           TIMESTAMP
, chg_dt                           DATE
, chg_tm                           TIMESTAMP
, adjust_claim_nbr                 BIGINT
, adjust_claim_seq_nbr             INTEGER
, adjust_claim_stat_id             CHAR(1)
, adjust_app_due_amt               DECIMAL(9,2)
, adjust_clt_due_amt               DECIMAL(9,2)
, rxclaim_instance_ind             SMALLINT
, prior_auth_nbr                   VARCHAR(11)
, refill_nbr                       VARCHAR(2)
, app_patient_pay_amt              DECIMAL(9,2)
, clt_patient_pay_amt              DECIMAL(9,2)
, contract_pbp_sk                  BIGINT NOT NULL
);

