DROP TABLE ${STAGING_SCHEMA}.pc_uhg_pbm_cl_cpp_work_opioid_u;

CREATE TABLE ${STAGING_SCHEMA}.pc_uhg_pbm_cl_cpp_work_opioid_u
( cpp_pc_uhg_pbm_cl_cpp_work_opioid_sk BIGINT NOT NULL
, px_commit_datetime               TIMESTAMP
, px_save_datetime                 TIMESTAMP
, px_cover_inskey                  NVARCHAR(255)
, px_covered_count                 DECIMAL(18)
, px_covered_count_open            DECIMAL(18)
, px_covered_count_unsatisfied     DECIMAL(18)
, px_create_datetime               TIMESTAMP
, px_create_opname                 NVARCHAR(128)
, px_create_operator               NVARCHAR(128)
, px_create_system_id              VARCHAR(32)
, px_flow_count                    DECIMAL(18)
, px_ins_name                      NVARCHAR(128)
, px_obj_class                     NVARCHAR(96)
, px_update_datetime               TIMESTAMP
, px_update_opname                 NVARCHAR(128)
, px_update_operator               NVARCHAR(128)
, px_update_system_id              VARCHAR(32)
, px_urgency_work                  DECIMAL(18)
, py_ack_timestamp                 TIMESTAMP
, py_age_from_date                 TIMESTAMP
, py_charge_amount                 DECIMAL(18)
, py_charge_to                     NVARCHAR(64)
, py_contact_channel               NVARCHAR(64)
, py_contact_type                  NVARCHAR(64)
, py_cus_level                     NVARCHAR(32)
, py_customer                      NVARCHAR(128)
, py_customer_enterprise           NVARCHAR(32)
, py_customer_name                 NVARCHAR(64)
, py_customer_org                  NVARCHAR(32)
, py_customer_satisfied_timestamp  TIMESTAMP
, py_description                   NVARCHAR(255)
, py_effort_actual                 DECIMAL(18)
, py_effort_estimate               DECIMAL(18)
, py_effort_estimate_timestamp     TIMESTAMP
, py_elapsed_customer_ack          DECIMAL(18)
, py_elapsed_customer_unsatisfied  DECIMAL(18)
, py_elapsed_past_deadline         DECIMAL(18)
, py_elapsed_past_goal             DECIMAL(18)
, py_elapsed_status_new            DECIMAL(18)
, py_elapsed_status_open           DECIMAL(18)
, py_elapsed_status_pending        DECIMAL(18)
, py_event_id                      VARCHAR(32)
, py_folder_type                   VARCHAR(32)
, py_id                            NVARCHAR(32)
, py_label                         NVARCHAR(64)
, py_orig_division                 VARCHAR(32)
, py_orig_org                      VARCHAR(32)
, py_orig_org_unit                 VARCHAR(32)
, py_orig_user_division            VARCHAR(32)
, py_orig_userid                   NVARCHAR(128)
, py_orig_user_workgroup           NVARCHAR(64)
, py_owner_division                VARCHAR(32)
, py_owner_org                     VARCHAR(32)
, py_owner_org_unit                VARCHAR(32)
, py_primary_contact               NVARCHAR(64)
, py_problem_reason                NVARCHAR(64)
, py_problem_source                NVARCHAR(64)
, py_problem_type                  NVARCHAR(64)
, py_reopen_count                  DECIMAL(18)
, py_reopen_timestamp              TIMESTAMP
, py_resolution_complexity         VARCHAR(8)
, py_resolution_cost               DECIMAL(18)
, py_resolved_division             VARCHAR(32)
, py_resolved_org                  VARCHAR(32)
, py_resolved_org_unit             VARCHAR(32)
, py_resolved_time                 VARCHAR(32)
, py_resolved_timestamp            TIMESTAMP
, py_resolved_userid               NVARCHAR(128)
, py_resolved_user_workgroup       NVARCHAR(64)
, py_root_cause                    NVARCHAR(64)
, py_sla_deadline                  TIMESTAMP
, py_sla_goal                      TIMESTAMP
, py_sla_name                      VARCHAR(32)
, py_status_customersat            VARCHAR(32)
, py_status_work                   NVARCHAR(32)
, py_worklist_date1                VARCHAR(8)
, py_worklist_datetime1            TIMESTAMP
, py_worklist_datetime2            TIMESTAMP
, py_worklist_decimal1             DECIMAL(18)
, py_worklist_decimal2             DECIMAL(18)
, py_worklist_integer1             DECIMAL(18)
, py_worklist_text1                NVARCHAR(128)
, py_worklist_text2                NVARCHAR(128)
, py_worklist_text3                NVARCHAR(128)
, px_current_stage_label           NVARCHAR(128)
, px_current_stage                 VARCHAR(32)
, pz_ins_key                       NVARCHAR(255)
, product_name                     NVARCHAR(32)
, program_name                     NVARCHAR(32)
, client_name                      NVARCHAR(32)
, src_env_id                       VARCHAR(32)
, carrier_id                       VARCHAR(32)
, acct_id                          VARCHAR(32)
, emplyr_group_id                  VARCHAR(32)
, member_id                        VARCHAR(32)
, cpp_member_sk                    BIGINT NOT NULL
, appointment_end_time             TIMESTAMP
, member_state                     VARCHAR(32)
, search_name                      NVARCHAR(50)
, max_call_attempts                DECIMAL(18)
, intvn_idntfn_id                  VARCHAR(32)
, cpp_intvn_idntfn_sk              BIGINT NOT NULL
, plan_first_mention               NVARCHAR(256)
, case_owner                       NVARCHAR(32)
, client_id                        VARCHAR(32)
, intervene_date                   TIMESTAMP
, intvn_name                       VARCHAR(50)
, no_of_call_attempts              DECIMAL(18)
, no_of_consulted_providers        DECIMAL(18)
, no_of_provider_corr_sent         DECIMAL(18)
, member_notification_letter_sent  VARCHAR(32)
, no_of_providers_responded        DECIMAL(18)
, is_committee_review              VARCHAR(32)
, reason_code                      VARCHAR(32)
, case_closed_date                 TIMESTAMP
, l3_case_type                     VARCHAR(70)
, appointment_date                 TIMESTAMP
, job_id                           DECIMAL(38)
, src_env_sk                       BIGINT
, insert_ts                        TIMESTAMP
, update_ts                        TIMESTAMP
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
);

