DROP TABLE ${STAGING_SCHEMA}.f_integ_accm_svng_claim_trx_i;

CREATE TABLE ${STAGING_SCHEMA}.f_integ_accm_svng_claim_trx_i
( claim_nbr                        BIGINT
, claim_seq_nbr                    INTEGER
, claim_stat_id                    CHAR(1)
, cag_sk                           BIGINT
, mbr_sk                           BIGINT
, isa_create_dt                    DATE
, isa_create_tm                    TIME
, isa_send_dt                      DATE
, isa_send_tm                      TIME
, isa_accum_seg_cnt                INTEGER
, isa_savacc_seg_cnt               INTEGER
, isa_record_src                   VARCHAR(3)
, isa_record_id                    VARCHAR(50)
, carrier_id                       VARCHAR(30)
, account_id                       VARCHAR(40)
, employer_group_id                VARCHAR(30)
, client_benefit_cd_sk             BIGINT
, patient_id                       VARCHAR(20)
, patient_fam_id                   VARCHAR(25)
, patient_last_nm                  VARCHAR(25)
, patient_first_nm                 VARCHAR(25)
, patient_pers_cd                  VARCHAR(3)
, patient_rel_cd                   CHAR(1)
, patient_sex                      CHAR(1)
, patient_dob_dt                   DATE
, patient_ssn                      VARCHAR(10)
, subscriber_id                    VARCHAR(18)
, subscriber_last_nm               VARCHAR(25)
, subscriber_first_nm              VARCHAR(15)
, subscriber_pers_cd               VARCHAR(3)
, subscriber_sex                   CHAR(1)
, subscriber_dob_dt                DATE
, subscriber_ssn                   VARCHAR(10)
, isa_fill_dt                      DATE
, isa_submit_dt                    DATE
, isa_rx_qlfr                      CHAR(1)
, isa_rx_nbr                       VARCHAR(12)
, refill_nbr                       VARCHAR(2)
, isa_phr_qlfr                     CHAR(2)
, phr_sk                           BIGINT
, prod_sk                          BIGINT
, app_due_amt                      DECIMAL(15,2)
, approved_dft_amt                 DECIMAL(15,2)
, dispensing_fee_amt               DECIMAL(15,2)
, flat_sls_tax_amt                 DECIMAL(15,2)
, incentive_amt                    DECIMAL(15,2)
, tot_other_amt                    DECIMAL(15,2)
, prof_svc_fee_amt                 DECIMAL(15,2)
, submitted_uc_amt                 DECIMAL(15,2)
, app_pat_pay_amt                  DECIMAL(15,2)
, app_copay_flat_amt               DECIMAL(15,2)
, app_copay_pct_amt                DECIMAL(15,2)
, copay_sched_nm                   VARCHAR(10)
, deductible_amt                   DECIMAL(15,2)
, overcap_amt                      DECIMAL(15,2)
, psc_amt                          DECIMAL(15,2)
, app_amt_atr_sls_tax              DECIMAL(15,2)
, sa_pay_amt                       DECIMAL(15,2)
, isa_filler                       VARCHAR(100)
, isa_final_pln_cd                 VARCHAR(10)
, isa_accum_seg_1                  VARCHAR(248)
, isa_accum_seg_2                  VARCHAR(248)
, isa_accum_seg_3                  VARCHAR(248)
, isa_accum_seg_4                  VARCHAR(248)
, isa_acct_seg_1                   VARCHAR(219)
, isa_acct_seg_2                   VARCHAR(219)
, isa_acct_seg_3                   VARCHAR(219)
, isa_acct_seg_4                   VARCHAR(219)
, isa_acct_seg_5                   VARCHAR(219)
, isa_acct_seg_6                   VARCHAR(219)
, isa_acct_seg_7                   VARCHAR(219)
, isa_acct_seg_8                   VARCHAR(219)
, isa_acct_seg_9                   VARCHAR(219)
, isa_acct_seg_10                  VARCHAR(219)
, src_rec_create_ts                TIMESTAMP
, src_rec_update_ts                TIMESTAMP
, src_env_sk                       BIGINT NOT NULL
, insert_ts                        TIMESTAMP NOT NULL
, update_ts                        TIMESTAMP NOT NULL
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
);

