DROP TABLE ${STAGING_SCHEMA}.D_PLAN_PREF_FRMLRY_GPI_LIST_U;

CREATE TABLE ${STAGING_SCHEMA}.D_PLAN_PREF_FRMLRY_GPI_LIST_U
(
	PLN_PREF_FRMLRY_GPI_LIST_SK BIGINT NOT NULL
,	PLN_SK BIGINT NOT NULL
,	PLN_CD CHARACTER VARYING(10) NOT NULL
,	PLN_EFF_DT DATE NOT NULL
,	PFG_GPI_LIST_NM CHARACTER VARYING(10)
,	PFG_SEQ_NBR INTEGER
,	PFG_MSG_CD CHARACTER VARYING(10)
,	PFG_FROM_DT DATE
,	PFG_THRU_DT DATE
,	PFG_STS CHARACTER(1)
,	PFG_SEQ_SRCH INTEGER
,	PFG_CMP_CRTR CHARACTER(1)
,	PFG_PLN_DFLT_LIST CHARACTER VARYING(10)
,	SRC_ENV_SK BIGINT NOT NULL
,	INSERT_TS TIMESTAMP NOT NULL
,	UPDATE_TS TIMESTAMP NOT NULL
,	INSERT_UID CHARACTER VARYING(20)
,	UPDATE_UID CHARACTER VARYING(20)
,	RUN_ID BIGINT
,	REC_STAT_CD BYTEINT
)
DISTRIBUTE ON (PLN_SK);
