DROP TABLE ${STAGING_SCHEMA}.D_PLAN_PHARMACY_NTWK_DTL_u;

CREATE TABLE ${STAGING_SCHEMA}.D_PLAN_PHARMACY_NTWK_DTL_u
( PLN_PHR_NTWK_SK               BIGINT NOT NULL
, PLN_CD                        CHARACTER VARYING(10)
, PLN_EFF_DT                    DATE
, PLN_SK                        BIGINT
, PHR_NTWK_PRTY                 CHARACTER(1)
, PLN_NTWK_TYPE                 CHARACTER VARYING(2)
, PHN_PHR_NTWK_uD               CHARACTER VARYING(6)
, PHN_SEQ_NBR                   INTEGER
, PLN_PHR_NTWK_LIST_CD          CHARACTER VARYING(10)
, PLN_PHR_NTWK_LIST_TYPE        CHARACTER VARYING(2)
, RX5_SEQ_NBR                   INTEGER
, PLN_PHR_NTWK_LIST_QLFR        CHARACTER(1)
, PHR_PRICE_SCHD                CHARACTER VARYING(10)
, PHR_PAT_PAY                   CHARACTER VARYING(10)
, MSG_CD                        CHARACTER VARYING(10)
, MSG_TYPE                      CHARACTER(1)
, CLT_PRICE_SCHD                CHARACTER VARYING(10)
, CLT_PAT_PAY                   CHARACTER VARYING(10)
, PRICE_BASIS_SCHD              CHARACTER VARYING(10)
, DEDUCTIBLE                    CHARACTER VARYING(10)
, DEDUCTIBLE_ACCM_CD            CHARACTER VARYING(10)
, OUT_OF_POCKET                 CHARACTER VARYING(10)
, OOP_ACCM_CD                   CHARACTER VARYING(10)
, BEN_MAX                       CHARACTER VARYING(10)
, BEN_MAX_ACCM_CD               CHARACTER VARYING(10)
, LFTM_BEN_MAX                  CHARACTER VARYING(10)
, LFTM_BEN_MAX_ACCM_CD          CHARACTER VARYING(10)
, FROM_DT                       DATE
, THRU_DT                       DATE
, STATUS                        CHARACTER(1)
, DISCOUNT_TBL_uD               CHARACTER VARYING(10)
, PHR_PROF_SRVS_FEE_TBL         CHARACTER VARYING(10)
, CLT_PROF_SRVS_FEE_TBL         CHARACTER VARYING(10)
, STATE_LIST                    CHARACTER VARYING(10)
, STATE_LIST_TYPE               CHARACTER VARYING(1)
, PHR_DUR_PPS_FEE               CHARACTER VARYING(10)
, CLT_DUR_PPS_FEE               CHARACTER VARYING(10)
, SPRD_PRICING_FLG              CHARACTER(1)
, CLT2_PRICE_SCHD               CHARACTER VARYING(10)
, CLT3_PRICE_SCHD               CHARACTER VARYING(10)
, CLT_PAT_PAY_GRP_SCHD_uD       CHARACTER VARYING(10)
, CLT1_PRICE_GRP_SCHD_uD        CHARACTER VARYING(10)
, CLT2_PRICE_GRP_SCHD_uD        CHARACTER VARYING(10)
, CLT3_PRICE_GRP_SCHD_uD        CHARACTER VARYING(10)
, PHR_PAT_PAY_GRP_SCHD_uD       CHARACTER VARYING(10)
, PHR_PRICE_GRP_SCHD_uD         CHARACTER VARYING(10)
, MAX_DAYS                      INTEGER
, MAX_FILLS                     INTEGER
, USR_SEQ_NBR                   INTEGER
, QLFR_TYPE_SEQ                 INTEGER
, SRC_ENV_SK                    BIGINT NOT NULL
, INSERT_TS                     TIMESTAMP NOT NULL
, UPDATE_TS                     TIMESTAMP NOT NULL
, INSERT_UID                    CHARACTER VARYING(20)
, UPDATE_UID                    CHARACTER VARYING(20)
, RUN_uD                        BIGINT
, REC_STAT_CD                   BYTEINT
);
