/* user=Gandi, Sudhakar reportPath= queryName=Query1 REMOTE_ADDR= SERVER_NAME=rxtrackidw-prd.optum.com requestID=MM2qM9w8wvC84h4GCsCvhvwhl29jj9Gsq44ds28C */ 
SELECT
    V_D_CAG.CARRIER_ID AS Carrier_ID, 
    V_D_CAG.ACCOUNT_ID AS Account_ID, 
    V_D_CAG.EMPLOYER_GROUP_ID AS Group_ID, 
    V_D_CAG.EMPLOYER_GROUP_NM AS Group_Name, 
    V_F_CLAIM_TRANSACTION.SBM_DT_SK AS Date_Submitted_YYYYMMDD, 
    V_D_DATE_FILLED.CAL_MNTH_NM AS Filled_Month, 
    V_D_PLAN_DRUG_STATUS.PLN_DRG_STAT_CD AS Plan_Drug_Status, 
    V_D_PLAN_DRUG_STATUS.PLN_DRG_STAT_DESC AS Plan_Drug_Status_Desc, 
    V_D_PHARMACY.STAT_IND AS Pharmacy_Status, 
    SUM(V_F_CLAIM_TRANSACTION.CLT_DUE_AMT - (V_F_CLAIM_TRANSACTION.CLT_PATIENT_PAY_AMT - V_F_CLAIM_TRANSACTION.APP_PATIENT_PAY_AMT)) AS LICS__Low_Income_Subsidy__Amount, 
    SUM(V_F_CLAIM_TRANSACTION.CLT_DUE_AMT) AS Amount_Paid, 
    V_L_CLAIM_STATUS.CLAIM_STAT_ID AS RxCLAIM_Status, 
    V_D_DATE_SUBMITTED.CAL_DAY_STR AS Date_Submitted_MM_DD_YYYY, 
    V_F_CLAIM_TRANSACTION.FILLED_DT_SK AS Date_of_Fill_YYYYMMDD
FROM
    ORX_IDW_DM_PRD.ADMIN.D_CAG V_D_CAG
        INNER JOIN ORX_IDW_DM_PRD.ADMIN.F_CLAIM_TRANSACTION V_F_CLAIM_TRANSACTION
        ON V_D_CAG.CAG_SK = V_F_CLAIM_TRANSACTION.CAG_SK
            INNER JOIN ORX_IDW_DM_PRD.ADMIN.D_DATE V_D_DATE_FILLED
            ON V_D_DATE_FILLED.DT_SK = V_F_CLAIM_TRANSACTION.FILLED_DT_SK
                INNER JOIN ORX_IDW_DM_PRD.ADMIN.D_DATE V_D_DATE_SUBMITTED
                ON V_D_DATE_SUBMITTED.DT_SK = V_F_CLAIM_TRANSACTION.SBM_DT_SK
                    INNER JOIN ORX_IDW_DM_PRD.ADMIN.D_PHARMACY V_D_PHARMACY
                    ON V_D_PHARMACY.PHR_SK = V_F_CLAIM_TRANSACTION.PHR_SK  
                        INNER JOIN ORX_IDW_DM_PRD.ADMIN.D_PLAN_DRUG_STATUS V_D_PLAN_DRUG_STATUS
                        ON V_D_PLAN_DRUG_STATUS.PLN_DRG_STAT_SK = V_F_CLAIM_TRANSACTION.PLN_DRG_STAT_SK
                            INNER JOIN ORX_IDW_DM_PRD.ADMIN.L_CLAIM_STATUS V_L_CLAIM_STATUS
                            ON V_F_CLAIM_TRANSACTION.CLAIM_STAT_SK = V_L_CLAIM_STATUS.CLAIM_STAT_SK 
WHERE 
    V_F_CLAIM_TRANSACTION.SBM_DT_SK BETWEEN 20231001 AND 20231031 AND
    V_L_CLAIM_STATUS.CLAIM_STAT_ID IN ( 
        'X', 
        'P' ) AND
    V_D_CAG.CARRIER_ID IN ( 
        'MPDMMPOH', 
        'MPDMMPTX', 
        'MPDOHCSP', 
        'MPDTXCSP', 
        'PSI2300', 
        'PSI2302', 
        'PSI2303', 
        'UHGRV2306', 
        'MPDCSMS', 
        'MPDCSNM', 
        'MPDCSOH', 
        'MPDCSOK', 
        'MPDCSP', 
        'MPDCSPA', 
        'MPDCSRI', 
        'MPDCSTX', 
        'MPDCSWA', 
        'MPDCSWI', 
        'MPDECMA', 
        'MPDMA2CSP', 
        'MPDMACSP', 
        'MPDMMPNY', 
        'MPDACUAZ', 
        'MPDACUMI', 
        'MPDACUMS', 
        'MPDACUNJ', 
        'MPDACUNY', 
        'MPDACUOH', 
        'MPDACUPA', 
        'MPDACUTN', 
        'MPDACUWI', 
        'MPDCSDE', 
        'MPDCSFL', 
        'MPDCSHI', 
        'MPDCSKS', 
        'MPDCSLA', 
        'EXCGUHCMD', 
        'EXCGUHCMI', 
        'EXCGUHCNC', 
        'EXCGUHCOK', 
        'EXCGUHCTN', 
        'EXCGUHCTX', 
        'EXCGUHCVA', 
        'EXCGUHCWA', 
        'MPD2300', 
        'MPD2302', 
        'MPD2304', 
        'MPDACUAR', 
        'ACUVAC', 
        'ACUVAEC', 
        'ACUWA', 
        'ACUWABH', 
        'ACUWAC', 
        'CSFL', 
        'CSFLD', 
        'CSPWRAP', 
        'EXCGUHCAL', 
        'EXCGUHCAZ', 
        'EXCGUHCFL', 
        'EXCGUHCGA', 
        'EXCGUHCIL', 
        'EXCGUHCLA', 
        'ACUOH', 
        'ACUOHMMP', 
        'ACUPA', 
        'ACUPA1', 
        'ACUPAC', 
        'ACUPAHPA', 
        'ACURI', 
        'ACUSC', 
        'ACUSCCHP', 
        'ACUTX', 
        'ACUTXC', 
        'ACUTXEC', 
        'ACUTXSK', 
        'ACUVA', 
        'ACUMN', 
        'ACUMS', 
        'ACUMSCHP', 
        'ACUNC', 
        'ACUNE', 
        'ACUNEC', 
        'ACUNEEC', 
        'ACUNM', 
        'ACUNMC', 
        'ACUNMEC', 
        'ACUNV', 
        'ACUNY', 
        'ACUNYEPP', 
        'ACUNYM', 
        'ACUIA', 
        'ACUIAC', 
        'ACUIAEC', 
        'ACUIN', 
        'ACUKS', 
        'ACUKSC', 
        'ACUKSEC', 
        'ACUKY', 
        'ACULA', 
        'ACULAC', 
        'ACUMAEC', 
        'ACUMD', 
        'ACUMI', 
        'ACUMIC', 
        'ACUAZ1', 
        'ACUAZEC', 
        'ACUCA', 
        'ACUCAC', 
        'ACUCAEC', 
        'ACUDC', 
        'ACUDCA', 
        'ACUDCH', 
        'ACUDE', 
        'ACUDEC', 
        'ACUFL', 
        'ACUFLEC', 
        'ACUHI', 
        'ACUHIEC', 
        'ACUAZ', 
        'IEXUHCRMH', 
        'MPDRMTN', 
        'RMHCAID', 
        'RMHCHP', 
        'RMHWRP', 
        'ACUCO', 
        'ACUCOC', 
        'EXCGUHCMO', 
        'EXCGUHCMS', 
        'EXCGUHCKS', 
        'EXCGUHCOH', 
        'MPDMNCSP', 
        'EXCGUHCCO' ) AND
    V_F_CLAIM_TRANSACTION.FILLED_DT_SK BETWEEN 20230901 AND 20231031 
GROUP BY 
    V_D_CAG.CARRIER_ID, 
    V_D_CAG.ACCOUNT_ID, 
    V_D_CAG.EMPLOYER_GROUP_ID, 
    V_D_CAG.EMPLOYER_GROUP_NM, 
    V_F_CLAIM_TRANSACTION.SBM_DT_SK, 
    V_D_DATE_FILLED.CAL_MNTH_NM, 
    V_D_PLAN_DRUG_STATUS.PLN_DRG_STAT_CD, 
    V_D_PLAN_DRUG_STATUS.PLN_DRG_STAT_DESC, 
    V_D_PHARMACY.STAT_IND, 
    V_L_CLAIM_STATUS.CLAIM_STAT_ID, 
    V_D_DATE_SUBMITTED.CAL_DAY_STR, 
    V_F_CLAIM_TRANSACTION.FILLED_DT_SK
