DROP TABLE D_MEMBER_FORMULARY_XREF_U;

CREATE TABLE D_MEMBER_FORMULARY_XREF_U
(
	MBR_FRMLRY_SK BIGINT,
	CARRIER_ID CHARACTER VARYING(30),
	ACCOUNT_ID CHARACTER VARYING(40),
	EMPLOYER_GROUP_ID CHARACTER VARYING(30),
	MBR_ID CHARACTER VARYING(20),
	MBR_PRSN_CD CHARACTER VARYING(6),
	MBR_RELSHP_CD CHARACTER(1),
	MB_FIRST_NM CHARACTER VARYING(50),
	MB_LAST_NM CHARACTER VARYING(70),
	MBR_DT_OF_BRTH DATE,
	CLIENT_ID CHARACTER VARYING(7),
	FORMULARY_MBR_ID CHARACTER VARYING(20),
	JOB_NM CHARACTER VARYING(10),
	JOB_USR CHARACTER VARYING(20),
	JOB_NBR BIGINT,
	SRC_ADD_DT DATE,
	SRC_ENV_SK BIGINT NOT NULL,
	INSERT_TS TIMESTAMP NOT NULL,
	UPDATE_TS TIMESTAMP NOT NULL,
	INSERT_UID CHARACTER VARYING(20),
	UPDATE_UID CHARACTER VARYING(20),
	RUN_ID BIGINT,
	REC_STAT_CD BYTEINT,
	MBR_SK BIGINT,
	CAG_SK BIGINT,
	CARRIER_SK BIGINT,
	SEC_FLG SMALLINT
)
DISTRIBUTE ON RANDOM;
