CREATE TABLE ORX_IDW_DM_ETL_PRD.ADMIN.D_PROD_CAG_SPCLTY_XREF_GPI_FIX
(
	PROD_CAG_SK BIGINT NOT NULL,
	CAG_SK BIGINT NOT NULL,
	PROD_SK BIGINT NOT NULL,
	PROD_ID CHARACTER VARYING(20),
	PROD_ID_QLFR_CD CHARACTER VARYING(2),
	GPI_NO CHARACTER VARYING(14),
	GPI_SK BIGINT,
	SPCLTY_PROD_RPTG_IND CHARACTER(1) NOT NULL,
	SPCLTY_PROD_RPTG_NM CHARACTER VARYING(35) NOT NULL,
	SRC_ENV_SK BIGINT NOT NULL,
	INSERT_TS TIMESTAMP NOT NULL,
	INSERT_UID CHARACTER VARYING(20),
	RUN_ID NUMERIC(19,0),
	UPDATE_TS TIMESTAMP NOT NULL,
	UPDATE_UID CHARACTER VARYING(20),
	REC_STAT_CD BYTEINT
)
DISTRIBUTE ON (CAG_SK);



