CREATE TABLE orx_idw_dm_etl_prd.ADMIN.ETL_090_CARRIER_FBENFT_PROCESS
(
	CARRIER_ID CHARACTER VARYING(30) NOT NULL DEFAULT '-'::"NVARCHAR",
	CARRIER_NM CHARACTER VARYING(50) NOT NULL
)
DISTRIBUTE ON (CARRIER_ID);
