
UPDATE ORX_IDW_DM_PRD..F_PA_CORRESPONDENCE_DETAIL  T
SET T.CAG_SK=S.CAG_SK,
T.UPDATE_TS=CURRENT_TIMESTAMP,
T.UPDATE_UID='FPACORR_CAG_UPDT'
FROM  ORX_IDW_DM_PRD..D_CAG S
WHERE T.CAR_CD = S.CARRIER_ID AND S.ACCOUNT_ID ='-' AND S.EMPLOYER_GROUP_ID='-' AND T.CAG_SK IS NULL;
