CREATE TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_APPL_ID_MFR_I AS SELECT * FROM ORX_IDW_DM_PRD..D_DRUG_APPL_ID_MFR;
CREATE TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_APPL_ID_MFR_U AS SELECT * FROM ORX_IDW_DM_PRD..D_DRUG_APPL_ID_MFR;
CREATE TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_APPL_ID_MFR_DI AS SELECT * FROM ORX_IDW_DM_PRD..D_DRUG_APPL_ID_MFR;
