DROP TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_COST_SCHED_CRITERIA_I;

DROP TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_COST_SCHED_CRITERIA_U;

DROP TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_COST_SCHED_CRITERIA_DI;

CREATE TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_COST_SCHED_CRITERIA_I AS SELECT * FROM ORX_IDW_DM_PRD..D_DRUG_COST_SCHED_CRITERIA WHERE 1=2;

CREATE TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_COST_SCHED_CRITERIA_U AS SELECT * FROM ORX_IDW_DM_PRD..D_DRUG_COST_SCHED_CRITERIA WHERE 1=2;

CREATE TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_COST_SCHED_CRITERIA_DI AS SELECT * FROM ORX_IDW_DM_PRD..D_DRUG_COST_SCHED_CRITERIA WHERE 1=2;

DROP TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_PRICING_I;

DROP TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_PRICING_U;

DROP TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_PRICING_DI;

CREATE TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_PRICING_I AS SELECT * FROM ORX_IDW_DM_PRD..D_DRUG_PRICING WHERE 1=2;

CREATE TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_PRICING_U AS SELECT * FROM ORX_IDW_DM_PRD..D_DRUG_PRICING WHERE 1=2;

CREATE TABLE APP_ORX_IDW_ETL_PRD.D_DRUG_PRICING_DI AS SELECT * FROM ORX_IDW_DM_PRD..D_DRUG_PRICING WHERE 1=2;

DROP TABLE APP_ORX_IDW_ETL_PRD.L_DRUG_COST_SCHED_I;

DROP TABLE APP_ORX_IDW_ETL_PRD.L_DRUG_COST_SCHED_U;

DROP TABLE APP_ORX_IDW_ETL_PRD.L_DRUG_COST_SCHED_DI;

CREATE TABLE APP_ORX_IDW_ETL_PRD.L_DRUG_COST_SCHED_I AS SELECT * FROM ORX_IDW_DM_PRD..L_DRUG_COST_SCHED WHERE 1=2;

CREATE TABLE APP_ORX_IDW_ETL_PRD.L_DRUG_COST_SCHED_U AS SELECT * FROM ORX_IDW_DM_PRD..L_DRUG_COST_SCHED WHERE 1=2;

CREATE TABLE APP_ORX_IDW_ETL_PRD.L_DRUG_COST_SCHED_DI AS SELECT * FROM ORX_IDW_DM_PRD..L_DRUG_COST_SCHED WHERE 1=2;
