DROP TABLE ${STAGING_SCHEMA}.D_PLAN_FRMLRY_PGM_GPI_LIST_U;

CREATE TABLE ${STAGING_SCHEMA}.D_PLAN_FRMLRY_PGM_GPI_LIST_U
(
	PLN_FRMLRY_PGM_GPI_LIST_SK BIGINT NOT NULL
,	PLN_SK BIGINT NOT NULL
,	PLN_CD CHARACTER VARYING(10) NOT NULL
,	PLN_EFF_DT DATE NOT NULL
,	FPG_GPI_LIST_NM CHARACTER VARYING(10)
,	FPG_SEQ_NBR INTEGER
,	FPG_FROM_DT DATE
,	FPG_THRU_DT DATE
,	FPG_LIST_TYPE CHARACTER(1)
,	FPG_STS CHARACTER(1)
,	FPG_SEQ_SRCH INTEGER
,	FPG_LVL CHARACTER(1)
,	FPG_MSG_CD CHARACTER VARYING(10)
,	FPG_MSG_TYPE CHARACTER VARYING(1)
,	FPG_IFR_FILL_LMT INTEGER
,	FPG_IFR_EFF_QLFR CHARACTER(1)
,	FPG_IFR_FROM_DT DATE
,	FPG_IFR_MAX_DAYS_SPPLY INTEGER
,	FPG_PFR_DT_SRC CHARACTER(1)
,	FPG_PFR_SRC_FROM_DT DATE
,	FPG_PFR_FILLS_TYPE CHARACTER(1)
,	FPG_PFR_FILLS_DAYS INTEGER
,	FPG_PFR_FILLS_MAX INTEGER
,	FPG_DISCNT_TBL_ID CHARACTER VARYING(10)
,	FPG_PHR_PAT_PAY CHARACTER VARYING(10)
,	FPG_CLT_PAT_PAY CHARACTER VARYING(10)
,	FPG_PHR_NW_ID CHARACTER VARYING(6)
,	FPG_PHN_SEQ_NBR INTEGER
,	FPG_PHR_NW_IE CHARACTER(1)
,	FPG_SUPER_NW_ID CHARACTER VARYING(6)
,	FPG_SNH_SEQ_NBR INTEGER
,	FPG_SUPER_NW_IE CHARACTER(1)
,	SRC_ENV_SK BIGINT NOT NULL
,	INSERT_TS TIMESTAMP NOT NULL
,	UPDATE_TS TIMESTAMP NOT NULL
,	INSERT_UID CHARACTER VARYING(20)
,	UPDATE_UID CHARACTER VARYING(20)
,	RUN_ID BIGINT
,	REC_STAT_CD BYTEINT
)
DISTRIBUTE ON (PLN_SK);
