DROP TABLE ${STAGING_SCHEMA}.D_PLAN_MAINTENANCE_i;

CREATE TABLE ${STAGING_SCHEMA}.D_PLAN_MAINTENANCE_i
( PMN_PLAN_MAINT_SK             BIGINT NOT NULL
, PLN_SK                        BIGINT
, PLN_CD                        CHARACTER VARYING(10)
, PLN_EFF_DT                    DATE
, PMN_MAINT_DRUG_CD             CHARACTER(1)
, PMN_MULTI_SOURCE_CD           CHARACTER(1)
, PMN_SEQ_NBR                   INTEGER
, PMN_MINIMUM_DAYS              INTEGER
, PMN_MAINT_DRUG_STS            CHARACTER(1)
, PMN_MAX_DAYS_SUPPLY_1         INTEGER
, PMN_MAX_DAYS_SUPPLY_2         INTEGER
, PMN_NBR_PER_CAL_YEAR          INTEGER
, PMN_MAX_QTY                   INTEGER
, PMN_COMP_DAYS_SPL_QTY_FLG     CHARACTER(1)
, PMN_COPAY_SCHEDULE_NM         CHARACTER VARYING(10)
, PMN_STEP_NBR                  INTEGER
, PMN_FILL_QLFR                 CHARACTER(1)
, PMN_FILL_LIMIT_EFF_DT         DATE
, PMN_FILL_LIMIT_DAYS           INTEGER
, PHN_PHR_NTWRK_ID              CHARACTER VARYING(6)
, PHR_NTWRK_SEQ_NBR             INTEGER
, PMN_NBR_OF_FILLS              INTEGER
, PMN_MAINT_DRUG_IND            CHARACTER(1)
, GPI_LIST_ID                   CHARACTER VARYING(10)
, PMN_OVERRIDE_REFILL_LMT       CHARACTER(1)
, PMN_GPI_LIST_STS              CHARACTER(1)
, PMN_NDC_LIST_ID               CHARACTER VARYING(10)
, PMN_NDC_LIST_STS              CHARACTER(1)
, SNH_SUPER_NETWORK_ID          CHARACTER VARYING(6)
, SNH_SEQ_NBR                   INTEGER
, PMN_FROM_DT                   DATE
, PMN_THRU_DT                   DATE
, PMN_STS                       CHARACTER(1)
, PMN_SUPER_NDC_LIST_ID         CHARACTER VARYING(10)
, PMN_SUPER_GPI_LIST_ID         CHARACTER VARYING(10)
, PMN_MESSAGE_CODE              CHARACTER VARYING(10)
, PMN_MESSAGE_TYPE              CHARACTER(1)
, PMN_ALLOW_SCC_OVRD            CHARACTER(1)
, SC1_LIST                      CHARACTER VARYING(10)
, SRC_ENV_SK                    BIGINT NOT NULL
, INSERT_TS                     TIMESTAMP NOT NULL
, UPDATE_TS                     TIMESTAMP NOT NULL
, INSERT_UID                    CHARACTER VARYING(20)
, UPDATE_UID                    CHARACTER VARYING(20)
, RUN_ID                        BIGINT
, REC_STAT_CD                   BYTEINT
);
