DROP TABLE ${STAGING_SCHEMA}.f_wc_claim_transaction_i;

CREATE TABLE ${STAGING_SCHEMA}.f_wc_claim_transaction_i
( claim_nbr                        BIGINT
, claim_seq_nbr                    INTEGER
, claim_stat_id                    CHAR(1)
, carrier_sk                       BIGINT
, carrier_acct_sk                  BIGINT
, cag_sk                           BIGINT
, mbr_sk                           BIGINT
, sbm_dt_sk                        BIGINT
, pbr_spclty_sk                    BIGINT
, pcp_sk                           BIGINT
, phr_sk                           BIGINT
, gender_sk                        BIGINT
, age_band_sk                      BIGINT
, relationship_cd_sk               BIGINT
, fmly_type_sk                     BIGINT
, prod_sk                          BIGINT
, ntwk_sk                          BIGINT
, hm_dlvry_ind_sk                  BIGINT
, pbr_sk                           BIGINT
, phr_afflt_sk                     BIGINT
, ahfs_cd_sk                       BIGINT
, cost_basis_sk                    BIGINT
, cost_type_cd_sk                  BIGINT
, final_pln_sk                     BIGINT
, prior_auth_reason_cd             VARCHAR(2)
, cob_ind_sk                       BIGINT
, gpi_sk                           BIGINT
, gnrc_mdspn_ind_sk                BIGINT
, gnrc_ind_sk                      BIGINT
, clt_prc_typ_sk                   BIGINT
, daw_cd_sk                        BIGINT
, claim_stat_sk                    BIGINT
, compound_sk                      BIGINT
, days_of_supply_sk                BIGINT
, rej_cd1_sk                       BIGINT
, rej_cd2_sk                       BIGINT
, rej_cd3_sk                       BIGINT
, claim_cntr                       SMALLINT
, refill_nbr                       VARCHAR(2)
, drg_qty                          DECIMAL(11,3)
, rx_written_dt                    DATE
, rx_nbr                           VARCHAR(12)
, awp_unit_cost                    DECIMAL(24,8)
, extd_awp_cost                    DECIMAL(13,5)
, cost_type_unit_cost              DECIMAL(13,5)
, clt_cost_type_unit_cost          DECIMAL(13,5)
, clt_cost_type_code               VARCHAR(10)
, app_ingred_cost_paid             DECIMAL(9,2)
, app_dispensing_fee               DECIMAL(9,2)
, app_sales_tax_paid               DECIMAL(9,2)
, app_patient_pay_amt              DECIMAL(9,2)
, app_due_amt                      DECIMAL(9,2)
, app_copay_amt                    DECIMAL(9,2)
, app_attrib_prod_sel_amt          DECIMAL(9,2)
, app_other_payer_amt              DECIMAL(9,2)
, app_incentive_amt                DECIMAL(9,2)
, app_attrib_to_ded_amt            DECIMAL(9,2)
, app_exe_per_bft_amt              DECIMAL(9,2)
, clt_ingred_cost_paid             DECIMAL(9,2)
, clt_dispensing_fee               DECIMAL(9,2)
, clt_sales_tax_paid               DECIMAL(9,2)
, clt_patient_pay_amt              DECIMAL(9,2)
, clt_due_amt                      DECIMAL(9,2)
, clt_copay_amt                    DECIMAL(9,2)
, clt_attrib_prod_sel_amt          DECIMAL(9,2)
, clt_other_payer_amt              DECIMAL(9,2)
, clt_incentive_amt                DECIMAL(9,2)
, clt_attrib_to_ded_amt            DECIMAL(9,2)
, clt_exe_per_bft_amt              DECIMAL(9,2)
, family_deductible_amt            DECIMAL(9,2)
, individual_deductible_amt        DECIMAL(9,2)
, ded_flg                          CHAR(1)
, ben_max_flag                     CHAR(1)
, prior_auth_nbr                   VARCHAR(11)
, refill_max                       SMALLINT
, brnd_trade_nm_flag               CHAR(1)
, prc_qty                          DECIMAL(13,3)
, gen_cntr                         BYTEINT
, formulary_cntr                   BYTEINT
, tier_level                       INTEGER
, dx_cd                            VARCHAR(15)
, dx_cd_qlfr                       VARCHAR(2)
, rej_cnt                          SMALLINT
, rsp_msg_1                        VARCHAR(50)
, rsp_msg_2                        VARCHAR(50)
, rsp_msg_3                        VARCHAR(50)
, sbm_tm                           TIME
, inn_max_out_of_pocket_amt        DECIMAL(9,2)
, phr_price_src_sk                 BIGINT
, clt_price_src_sk                 BIGINT
, payee_id                         VARCHAR(12)
, contract_pbp_sk                  BIGINT
, mbr_carrier_uid                  BIGINT
, phr_rate                         DECIMAL(5,2)
, clt_rate                         DECIMAL(5,2)
, super_ntwk_sk                    BIGINT
, awp_extended_cost_ind            CHAR(1)
, dmr_ind_sk                       BIGINT
, formulary_flg                    CHAR(1)
, claim_origination_code_sk        BIGINT
, reversal_ind                     CHAR(1)
, recent_clm_flg                   CHAR(1)
, origin_cd                        CHAR(1)
, reported_gap_discount_amt        DECIMAL(9,2)
, filled_dt_sk                     BIGINT
, dur_flg                          CHAR(1)
, dur_key                          VARCHAR(18)
, fam_acc_life_benefit_amt         DECIMAL(9,2)
, fam_acc_benefit_ptd_amt          DECIMAL(9,2)
, ind_benefit_max_ptd_amt          DECIMAL(9,2)
, ind_acc_life_benefit_amt         DECIMAL(9,2)
, accum_oop                        DECIMAL(9,2)
, ind_life_ben_max_rem_amt         DECIMAL(9,2)
, ind_oop_rem_amt                  DECIMAL(9,2)
, out_of_pocket_max_flag           CHAR(1)
, phr_ntwrk_gpi_list               VARCHAR(10)
, phr_ntwrk_ndc_list               VARCHAR(10)
, cmpd_typ_submd                   VARCHAR(2)
, injury_dt                        DATE
, orig_pmt_dt                      DATE
, sub_reversal_dt                  DATE
, delay_rsn_cd                     CHAR(1)
, dispng_stat                      CHAR(1)
, incdnt_id                        VARCHAR(25)
, zro_bal_claims_flag              BYTEINT
, basis_of_cost_cd                 VARCHAR(2)
, basis_of_reim_cd                 VARCHAR(2)
, client_pricing_flg               CHAR(1)
, clt_pct_copay_amt                DECIMAL(9,2)
, clt_amt_covrg_gap                DECIMAL(9,2)
, clt_attrd_sls_tax                DECIMAL(9,2)
, clt_flat_copay_amt               DECIMAL(9,2)
, clt_oth_amt                      DECIMAL(9,2)
, spclty_phr_corp_ind              CHAR(1)
, clt_tot_cob_amt                  DECIMAL(9,2)
, clt_wthd_amt                     DECIMAL(9,2)
, clt_ppay_amt_psc_brnd_npf        DECIMAL(9,2)
, mail_ordr_corp_ind               CHAR(1)
, retl_90_corp_ind                 CHAR(1)
, phr_amt_sls_tax                  DECIMAL(9,2)
, phr_amt_covrg_gap                DECIMAL(9,2)
, phr_copay_flat_dllr_amt          DECIMAL(9,2)
, phr_copay_pct_dllr_amt           DECIMAL(9,2)
, phr_oth_amt                      DECIMAL(9,2)
, phr_tot_cob_amt                  DECIMAL(9,2)
, phr_wthd_amt                     DECIMAL(9,2)
, phr_ppay_amt_psc_brnd_npf        DECIMAL(9,2)
, cmpo_last_seq                    BIGINT
, rebill_cost_src                  CHAR(1)
, rebill_cost_typ                  VARCHAR(10)
, rebill_cost_typ_unit_cost        DECIMAL(13,5)
, rebill_dispng_fee                DECIMAL(9,2)
, rebill_incent_fee                DECIMAL(9,2)
, rebill_ingrd_cost_pd             DECIMAL(9,2)
, rebill_prc_typ                   VARCHAR(10)
, rebill_sls_tax_pd                DECIMAL(9,2)
, rebill_due_amt                   DECIMAL(9,2)
, rebill_oth_amt                   DECIMAL(9,2)
, msg_cd_1                         VARCHAR(10)
, msg_cd_2                         VARCHAR(10)
, msg_cd_3                         VARCHAR(10)
, rebill_drug_cost_percent         DECIMAL(5,2)
, prev_fill_1_dt                   DATE
, prev_fill_2_dt                   DATE
, prev_fill_3_dt                   DATE
, fam_benefit_max_rem_amt          DECIMAL(9,2)
, fam_deductible_rem_amt           DECIMAL(9,2)
, fam_life_ben_max_rem_amt         DECIMAL(9,2)
, fam_lbft_tran_max_amt            DECIMAL(9,2)
, fam_oop_rem_amt                  DECIMAL(9,2)
, ind_benefit_max_rem_amt          DECIMAL(9,2)
, ind_deductible_rem_amt           DECIMAL(9,2)
, ind_lbft_tran_max_amt            DECIMAL(9,2)
, prev_fill_1_qty                  DECIMAL(11,3)
, prev_fill_2_qty                  DECIMAL(11,3)
, prev_fill_3_qty                  DECIMAL(11,3)
, incdt_id                         VARCHAR(25)
, dt_of_injry                      DATE
, clm_ref_id_nbr                   VARCHAR(30)
, empr_nm                          VARCHAR(30)
, empr_addr                        VARCHAR(30)
, empr_city                        VARCHAR(20)
, empr_st_cd                       VARCHAR(2)
, empr_zip                         VARCHAR(18)
, empr_phn                         BIGINT
, alt_prod_typ                     CHAR(1)
, alt_prod_cd                      VARCHAR(13)
, diag_cd_qlfr                     VARCHAR(2)
, diag_cd                          VARCHAR(15)
, incdt_injry_from_dt              DATE
, incdt_injry_thru_dt              DATE
, incdt_carrier_id                 VARCHAR(10)
, incdt_claim_ref_id               VARCHAR(30)
, incdt_empr_nm                    VARCHAR(30)
, incdt_empr_addr                  VARCHAR(30)
, incdt_empr_city                  VARCHAR(20)
, incdt_empr_st_cd                 VARCHAR(2)
, incdt_empr_zip                   VARCHAR(9)
, incdt_st_of_venue                VARCHAR(2)
, incdt_refrl_stat_cd              VARCHAR(2)
, incdt_adjr_nm                    VARCHAR(25)
, incdt_adjr_phn_nbr               BIGINT
, pln_cd                           VARCHAR(10)
, pln_eff_dt                       DATE
, fee_amt                          DECIMAL(7,2)
, st_fee_amt                       DECIMAL(7,2)
, usl_cstmry_amt                   DECIMAL(7,2)
, usr_defd_fld                     VARCHAR(10)
, incdt_mbr_wrk_phn_nbr            BIGINT
, incdt_mbr_wrk_phn_ext            INTEGER
, incdt_empr_policy_id             BIGINT
, incdt_mco_nbr                    BIGINT
, incdt_asgmnt                     BIGINT
, incdt_act_ind_dt                 DATE
, incdt_act_ind                    VARCHAR(2)
, incdt_stat_cd                    VARCHAR(2)
, incdt_kpro_end_dt                DATE
, incdt_cvrg_cd                    VARCHAR(2)
, incdt_rehab_flg                  CHAR(1)
, incdt_cvrg_typ                   CHAR(1)
, incdt_fund_typ                   CHAR(1)
, incdt_hndcp_pct                  INTEGER
, incdt_ncci_cd                    INTEGER
, incdt_dod                        DATE
, incdt_lst_pd_dt_of_srvc          DATE
, incdt_src_cd                     CHAR(1)
, incdt_rel_incdt_id               VARCHAR(30)
, incdt_stat_of_limit_dt           DATE
, incdt_acdt_typ                   CHAR(1)
, pat_ssn                          INTEGER
, cdhldr_id                        VARCHAR(20)
, aprvd_icd_9_cd                   VARCHAR(6)
, prov_id                          VARCHAR(11)
, src_env_sk                       BIGINT NOT NULL
, insert_ts                        TIMESTAMP NOT NULL
, update_ts                        TIMESTAMP NOT NULL
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
);

