DROP TABLE ${STAGING_SCHEMA}.D_PHARMACY_NTWK_GPI_DTL_i;

CREATE TABLE ${STAGING_SCHEMA}.D_PHARMACY_NTWK_GPI_DTL_i
( PHR_NTWK_GPI_SK               BIGINT NOT NULL
, PHR_GPI_LIST_NM               CHARACTER VARYING(10)
, PHR_GPI_ID                    CHARACTER VARYING(14)
, SEQ_NBR                       INTEGER
, STATUS                        CHARACTER(1)
, EFF_DT                        DATE
, THRU_DT                       DATE
, PHR_GPI_NM                    CHARACTER VARYING(60)
, PHR_PRICE_SCHD                CHARACTER VARYING(10)
, PHR_PAT_PAY                   CHARACTER VARYING(10)
, CLT_PRICE_SCHD                CHARACTER VARYING(10)
, CLT_PAT_PAY                   CHARACTER VARYING(10)
, PHR_PROF_SRVS_FEE_TBL         CHARACTER VARYING(10)
, CLT_PROF_SRVS_FEE_TBL         CHARACTER VARYING(10)
, PHR_DUR_PPS_FEE               CHARACTER VARYING(10)
, CLT_DUR_PPS_FEE               CHARACTER VARYING(10)
, RXPRICE_PHR                   CHARACTER VARYING(10)
, RXPRICE_CLT                   CHARACTER VARYING(10)
, CLT2_PRICE_SCHD               CHARACTER VARYING(10)
, CLT3_PRICE_SCHD               CHARACTER VARYING(10)
, CLT_PAT_PAY_GRP_SCHD_ID       CHARACTER VARYING(10)
, CLT1_PRICE_GRP_SCHD_ID        CHARACTER VARYING(10)
, CLT2_PRICE_GRP_SCHD_ID        CHARACTER VARYING(10)
, CLT3_PRICE_GRP_SCHD_ID        CHARACTER VARYING(10)
, PHR_PAT_PAY_GRP_SCHD_ID       CHARACTER VARYING(10)
, PHR_PRICE_GRP_SCHD_ID         CHARACTER VARYING(10)
, SRC_ENV_SK                    BIGINT NOT NULL
, INSERT_TS                     TIMESTAMP NOT NULL
, UPDATE_TS                     TIMESTAMP NOT NULL
, INSERT_UID                    CHARACTER VARYING(20)
, UPDATE_UID                    CHARACTER VARYING(20)
, RUN_ID                        BIGINT
, REC_STAT_CD                   BYTEINT
);
