DROP TABLE ${STAGING_SCHEMA}.D_PGT_PLAN_GPI_LIST_i;

CREATE TABLE ${STAGING_SCHEMA}.D_PGT_PLAN_GPI_LIST_i
( PGT_PLAN_GPI_SK     BIGINT NOT NULL
, PLN_SK              BIGINT
, PLN_CD              CHARACTER VARYING(10)
, PLN_EFF_DT          DATE
, PGT_LIST_TYPE       CHARACTER VARYING(2)
, PGL_GPI_LIST_NM     CHARACTER VARYING(10)
, PGT_SEQ_NBR         INTEGER
, PGT_FROM_DT         DATE
, PGT_THRU_DT         DATE
, PGT_STATUS          CHARACTER(1)
, PGT_PRCSSNG_QLFR    CHARACTER(1)
, PGT_SEQ_SEARCH      INTEGER
, PGT_PLN_DEFAULT_LIST CHARACTER VARYING(10)
, PGT_NON_PRF_BRND_IND CHARACTER(1)
, PGT_CNTNGNT_THRPY_IND CHARACTER(1)
, PGT_DAILY_DOSE_IND    CHARACTER(1)
, PGT_GRACE_PERIOD_IND  CHARACTER(1)
, PGT_GRACE_PERIOD_DAYS INTEGER
, PGT_GRACE_PERIOD_EFF_DT DATE
, PGT_GRP_SCHEDULE_ID     CHARACTER VARYING(10)
, PGT_FIRST_FILL_DRUG_STS CHARACTER(1)
, PGT_SUPPL_REJ_CDE_TBL   CHARACTER VARYING(10)
, PGT_NON_PRF_BRAND_LVL   CHARACTER(1)
, PGT_NON_PRF_BRAND_WC    CHARACTER VARYING(2)
, PGT_CNTNGNT_THRPY_LVL   CHARACTER(1)
, PGT_CNTNGNT_THRPY_WC    CHARACTER VARYING(2)
, PGT_DAILY_DOSE_LVL      CHARACTER(1)
, PGT_DAILY_DOSE_WC       CHARACTER VARYING(2)
, PGT_PRIOR_STTHRPY_EXEMPT CHARACTER(1)
, PGT_PRIOR_STTHRPY_DRG_STS CHARACTER(1)
, PGT_PERIOD_QTY_MAX_MULT   INTEGER
, SRC_ENV_SK                BIGINT NOT NULL
, INSERT_TS                 TIMESTAMP NOT NULL
, UPDATE_TS                 TIMESTAMP NOT NULL
, INSERT_UID                CHARACTER VARYING(20)
, UPDATE_UID                CHARACTER VARYING(20)
, RUN_ID                    BIGINT
, REC_STAT_CD               BYTEINT
);
