DROP TABLE ${STAGING_SCHEMA}.D_GP2_GPI_LIST_u;

CREATE TABLE ${STAGING_SCHEMA}.D_GP2_GPI_LIST_u
( GP2_GPI_SK             BIGINT NOT NULL
, GPI_LIST_uD            CHARACTER VARYING(10)
, GP2_GPI_NBR            CHARACTER VARYING(14)
, GP2_GPI_NM             CHARACTER VARYING(60)
, GP2_GPI_FROM_DT        DATE
, GP2_GPI_THRU_DT        DATE
, GP2_MSG_CD             CHARACTER VARYING(10)
, GP2_MSG_TYPE           CHARACTER(1)
, SRC_ENV_SK             BIGINT NOT NULL
, INSERT_TS              TIMESTAMP NOT NULL
, UPDATE_TS              TIMESTAMP NOT NULL
, INSERT_UID             CHARACTER VARYING(20)
, UPDATE_UID             CHARACTER VARYING(20)
, RUN_uD                 BIGINT
, REC_STAT_CD            BYTEINT
);
