DROP TABLE ${STAGING_SCHEMA}.D_PNT_PLAN_NDC_LIST_u;

CREATE TABLE ${STAGING_SCHEMA}.D_PNT_PLAN_NDC_LIST_u
( PNT_PLAN_NDC_SK               BIGINT NOT NULL
, PLN_SK                        BIGINT
, PLN_CD                        CHARACTER VARYING(10)
, PLN_EFF_DT                    DATE
, PNT_LIST_TYPE                 CHARACTER VARYING(2)
, PNT_NDC_LIST_NM_10            CHARACTER VARYING(10)
, PNL_NDC_LIST_NM_6             CHARACTER VARYING(6)
, PNT_SEQ_NBR                   INTEGER
, PNT_FROM_DT                   DATE
, PNT_THRU_DT                   DATE
, PNT_STS                       CHARACTER(1)
, PNT_PRCSSNG_QLFR              CHARACTER(1)
, PNT_SEQ_SEARCH                INTEGER
, PNT_PLN_DEFAULT_LIST          CHARACTER VARYING(6)
, PNT_NON_PRF_BRAND_uND         CHARACTER(1)
, PNT_CNTNGNT_THRPY_uND         CHARACTER(1)
, PNT_DAILY_DOSE_uND            CHARACTER(1)
, PNT_GRACE_PERIOD_uND          CHARACTER(1)
, PNT_GRACE_PERIOD_DAYS         INTEGER
, PNT_GRACE_PERIOD_EFF_DT       DATE
, PNT_GRP_SCHEDULE_uD           CHARACTER VARYING(10)
, PNT_FIRST_FILL_DRUG_STS       CHARACTER(1)
, PNT_SUPPL_REJ_CDE_TBL         CHARACTER VARYING(10)
, PNT_NON_PRF_BRAND_LVL         CHARACTER(1)
, PNT_NON_PRF_BRAND_WC          CHARACTER VARYING(2)
, PNT_CNTNGNT_THRPY_LVL         CHARACTER(1)
, PNT_CNTNGNT_THRPY_WC          CHARACTER VARYING(2)
, PNT_DAILY_DOSE_LVL            CHARACTER(1)
, PNT_DAILY_DOSE_WC             CHARACTER VARYING(2)
, PNT_PRIOR_STTHRPY_EXEMPT      CHARACTER(1)
, PNT_PRIOR_STTHRPY_DRG_STS     CHARACTER(1)
, PNT_PERIOD_QTY_MAX_MULT       INTEGER
, SRC_ENV_SK                    BIGINT NOT NULL
, INSERT_TS                     TIMESTAMP NOT NULL
, UPDATE_TS                     TIMESTAMP NOT NULL
, INSERT_UID                    CHARACTER VARYING(20)
, UPDATE_UID                    CHARACTER VARYING(20)
, RUN_uD                        BIGINT
, REC_STAT_CD                   BYTEINT
);

