DROP TABLE ${STAGING_SCHEMA}.f_cms_pricing_accuracy_pde_i;

CREATE TABLE ${STAGING_SCHEMA}.f_cms_pricing_accuracy_pde_i
( pde_det_resp_sk                  BIGINT
, pde_resp_rec_type_sk             BIGINT
, pde_adj_del_sk                   BIGINT
, cms_pharmacy_cost_sk             BIGINT
, cms_drug_pricing_file_sk         BIGINT
, cms_prxy_ndc_mon_sk              BIGINT
, cms_stars_calendar_submission_sk BIGINT
, cms_prxy_ndc_sk                  BIGINT
, cms_ndc_sk                       BIGINT
, pde_prxy_ndc_sk                  BIGINT
, pde_ndc_sk                       BIGINT
, report_prxy_ndc_sk               INTEGER
, report_ndc_sk                    INTEGER
, pde_cag_sk                       BIGINT
, pde_phr_sk                       BIGINT
, claim_phr_sk                     BIGINT
, pde_pbp_sk                       BIGINT
, pde_compound_sk                  BIGINT
, pde_final_pln_sk                 BIGINT
, pde_residence_cd_sk              BIGINT
, pde_claim_nbr                    BIGINT
, pde_claim_seq_nbr_src            BIGINT
, pde_claim_stat_id                CHAR(1)
, pde_contract_id                  VARCHAR(5)
, pde_pbp_id                       VARCHAR(3)
, pde_carrier_id                   VARCHAR(9)
, pde_final_pln_cd                 VARCHAR(10)
, pde_prxy_ndc_id                  VARCHAR(20)
, pde_prxy_ndc_label_nm            VARCHAR(100)
, pde_ndc_id                       VARCHAR(20)
, pde_ndc_label_nm                 VARCHAR(100)
, pde_brand_generic_cd             CHAR(1)
, pde_phr_id                       VARCHAR(15)
, pde_phr_npi_id                   VARCHAR(10)
, pde_phr_svc_typ                  VARCHAR(2)
, pde_residence_cd                 VARCHAR(2)
, pde_residence_cd_desc            VARCHAR(100)
, pde_claim_sbm_dt                 DATE
, pde_filled_dt                    DATE
, pde_sbm_dt                       DATE
, pde_proc_dt                      DATE
, pde_crosstab_month               VARCHAR(2)
, pde_crosstab_year                VARCHAR(4)
, cal_start_dt                     DATE
, cal_end_dt                       DATE
, prod_directory_dt                DATE
, cms_segment_id                   VARCHAR(3)
, price_id                         VARCHAR(3)
, preferred_status_retail_flg      CHAR(1)
, phr_retail_flg                   CHAR(1)
, phr_mail_flg                     CHAR(1)
, phr_la_drugs_flg                 CHAR(1)
, phr_hi_flg                       CHAR(1)
, phr_ltc_flg                      CHAR(1)
, preferred_status_mail_flg        CHAR(1)
, pricing_file_mail_flg            CHAR(1)
, pde_drg_qty                      DECIMAL(11,3)
, pde_days_of_supply               SMALLINT
, mpf_days_of_supply               SMALLINT
, pde_ndc_unit_cost                DECIMAL(13,4)
, mpf_ndc_unit_cost                DECIMAL(13,4)
, pde_dispensing_fee               DECIMAL(8,4)
, mpf_dispensing_fee               DECIMAL(13,4)
, tot_pde_drug_cost                DECIMAL(13,4)
, tot_mpf_drug_cost                DECIMAL(13,4)
, tot_est_pde_cost                 DECIMAL(13,2)
, tot_est_mpf_cost                 DECIMAL(13,4)
, tot_est_discrepancy              DECIMAL(13,4)
, src_insert_ts                    TIMESTAMP
, src_env_sk                       BIGINT NOT NULL
, insert_ts                        TIMESTAMP NOT NULL
, update_ts                        TIMESTAMP NOT NULL
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
);

