DROP TABLE ${STAGING_SCHEMA}.f_claim_trx_common_dtl2_i;

CREATE TABLE ${STAGING_SCHEMA}.f_claim_trx_common_dtl2_i
( claim_nbr                        BIGINT
, claim_seq_nbr                    INTEGER
, ndc_list_id                      VARCHAR(10)
, maint_list_stat_cd               VARCHAR(1)
, next_refill_dt                   DATE
, gen_drg_cov_cd                   VARCHAR(1)
, nda_flg                          VARCHAR(1)
, nda_ovrd_flg                     VARCHAR(1)
, bla_flg                          VARCHAR(1)
, bla_ovrd_flg                     VARCHAR(1)
, pde_form_nform_stat_cd           VARCHAR(1)
, hic3_ovrd_flg                    VARCHAR(1)
, rx_otc_ind                       VARCHAR(1)
, phr_xref_vldn_flg                VARCHAR(1)
, sbm_original_rx_nbr              VARCHAR(12)
, cost_ovrd_ind                    VARCHAR(1)
, std_thrpc_cls_cd                 VARCHAR(2)
, tb_prequal_pass_flg              VARCHAR(1)
, medicaid_subrogation_flg         VARCHAR(1)
, unauthorized_pbr_flg             VARCHAR(1)
, mbr_tb_elgblty_flg               VARCHAR(1)
, suppress_ltr_flg                 VARCHAR(1)
, cob_data_flg                     VARCHAR(1)
, trans_ref_id                     VARCHAR(10)
, claim_pricing_flg                VARCHAR(1)
, gppc_id                          VARCHAR(10)
, incent_sched_id                  VARCHAR(10)
, dx_list_id                       VARCHAR(6)
, dx_list_qlfr_cd                  VARCHAR(1)
, short_cycle_prov_qlfr_cd         VARCHAR(1)
, short_cycle_prod_qlfr_cd         VARCHAR(1)
, short_cycle_clm_qlfr_cd          VARCHAR(1)
, short_cycle_disp_std_no          INTEGER
, discount_flg                     VARCHAR(1)
, rsp_pyr_id_qlfr_cd               VARCHAR(2)
, rsp_payer_id                     VARCHAR(10)
, phr_amt_due_sched_id             VARCHAR(10)
, phr_amt_due_step_no              INTEGER
, clt_amt_due_sched_id             VARCHAR(10)
, clt_amt_due_step_no              INTEGER
, pps_ds_ovrd_flg                  VARCHAR(1)
, clt_tax_ovrd_flg                 VARCHAR(1)
, multi_source_cd                  VARCHAR(1)
, dly_cst_shr_round_typ_flg        VARCHAR(1)
, dly_cst_shr_round_len_flg        VARCHAR(1)
, auto_pay_rejctn_flg              VARCHAR(1)
, bypass_acc_flg                   VARCHAR(1)
, biosimilar_prod_flg              VARCHAR(1)
, future_use_stat9_cd              VARCHAR(1)
, dx_typ1_cd                       VARCHAR(1)
, dx_typ2_cd                       VARCHAR(1)
, dx_typ3_cd                       VARCHAR(1)
, future_use_stat13_cd             VARCHAR(1)
, future_use_stat14_cd             VARCHAR(1)
, future_use_stat15_cd             VARCHAR(1)
, grace_perd_end_dt                DATE
, future_use2_cd                   VARCHAR(10)
, future_use3_cd                   VARCHAR(10)
, spread_pricing_flg               VARCHAR(1)
, spread_pricing_pct               DECIMAL(8,6)
, dcs_dly_prorate                  DECIMAL(12,4)
, him_seq_no                       INTEGER
, him_issuer_di                    VARCHAR(5)
, him_st_cd                        VARCHAR(2)
, him_prod_nbr                     VARCHAR(3)
, him_std_compnt                   VARCHAR(4)
, him_csr_lvl                      VARCHAR(2)
, him_aptc_ind                     VARCHAR(1)
, him_ethnicity_cd                 VARCHAR(2)
, him_pln_metal_ind                VARCHAR(1)
, him_grace_perd_ind               VARCHAR(2)
, src_env_sk                       BIGINT NOT NULL
, insert_ts                        TIMESTAMP NOT NULL
, update_ts                        TIMESTAMP NOT NULL
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
, cag_sk                           BIGINT
, mbr_sk                           BIGINT
, cred_455_ind                     VARCHAR(2)
, toc_claim_ind                    CHAR(1)
, toc_enr_typ_cd                   CHAR(1)
, toc_ovrd_drg_stat                CHAR(1)
, toc_prequal_ind                  CHAR(1)
, toc_ovrd_sched                   VARCHAR(10)
);

