scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_product_adjud.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.l_gender.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.l_dosage_form.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.l_compound.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.l_admin_route.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_profile_item.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_pref_pharmacy_config.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_pharmacy_super_ntwk_dtl.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_pharmacy_super_network.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_pharmacy_ntwk_dtl.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_pharmacy_network.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_frmlry_mgmt_svc.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_frmlry_mgmt_svc_profile.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_copay_config.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_cag_prod_ovrd.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_product.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_product_adjud.reduced.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_prod_ingredient.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_plan_rx_network.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_plan.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_pharmacy_rltnshp_dtl.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_pharmacy_relationship.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_pharmacy.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_pharmacy_affiliation.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_group_eligibility.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_gpi.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_cag.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_cag_gpi_ovrd.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_cag.daily.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_product.daily.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_gpi.daily.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_pharmacy.daily.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_pharmacy_rltnshp_dtl.daily.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_common.d_pharmacy_relationship.daily.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_hd.d_ms_drug.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxlink.l_cag_lob_xref.pset .
scp schakal1@apvrd55593:/etl/devel/appconf.distribution_idw_direct_v4/idw_direct/users/schakal1/orca/distribution/pset/bpe/replicate_table_pset/replicate.ids_rxclaim.d_gpi_gppc_pkg_dtl.pset .
