DROP TABLE ${STAGING_SCHEMA}.f_rpt_calpers_details_u;

CREATE TABLE ${STAGING_SCHEMA}.f_rpt_calpers_details_u
( report_id                        VARCHAR(10)
, pbm_calpers_id                   VARCHAR(10)
, claim_cycle_begin_date           VARCHAR(40)
, claim_cycle_end_date             VARCHAR(40)
, claim_schedule_number            VARCHAR(8)
, group_number                     VARCHAR(15)
, sub_account_number               VARCHAR(9)
, plan_description                 VARCHAR(30)
, claim_amount                     DECIMAL(15,2)
, transactional_fees               DECIMAL(15,2)
, overpayments                     DECIMAL(15,2)
, total_warrant_eft_amount         DECIMAL(15,2)
, payee_provider_subscriber        CHAR(1)
, subscriber_ssn                   VARCHAR(9)
, patient_ssn                      VARCHAR(9)
, patient_calpers_id               VARCHAR(20)
, patient_first_name               VARCHAR(15)
, patient_middle_name              VARCHAR(1)
, patient_last_name                VARCHAR(25)
, patient_date_of_birth            VARCHAR(40)
, claim_id                         CHAR(18)
, eft_trace_number                 VARCHAR(15)
, provider_name                    VARCHAR(60)
, provider_id_npi                  VARCHAR(12)
, tax_id                           VARCHAR(15)
, egwp_wrap_y_n                    CHAR(1)
, relationship_to_subscriber       CHAR(1)
, hicn                             VARCHAR(11)
, service_date_incurred            VARCHAR(40)
, claim_type                       VARCHAR(2)
, adjustments                      CHAR(1)
, payment_type                     CHAR(1)
, original_claim_schedule_number   VARCHAR(8)
, original_warrant_eft_trace_number VARCHAR(15)
, original_warrant_eft_issue_date  VARCHAR(40)
, drug_name                        VARCHAR(70)
, ndc                              VARCHAR(20)
, issuance_indicator               CHAR(1)
, payee_id                         VARCHAR(10)
, payee_name                       VARCHAR(60)
, file_id                          VARCHAR(50)
, src_env_sk                       BIGINT
, insert_ts                        TIMESTAMP
, update_ts                        TIMESTAMP
, insert_uid                       VARCHAR(20)
, update_uid                       VARCHAR(20)
, run_id                           BIGINT
, rec_stat_cd                      BYTEINT
);

