SELECT rcex1p.rxclaimnbr
     , rcex1p.clmseqnbr
     , rcex1p.claimsts
     , rcex1p.carrierid
     , rcex1p.accountid
     , rcex1p.groupid
     , rcex1p.memberid
     , rcex1p.datesbm
     , rcex1p.srvprovid
     , rctcdp.dqs5cd
     , rctcdp.dqs6cd
     , rctcdp.dqs7cd
     , rctcdp.dqs8cd
     , rcxpcp.qus5bu
     , rcxpcp.qus6bu
     , rcxpcp.qus7bu
     , rcxpcp.qudbsd
     , rcxpcp.qudcsd
     , rcxpcp.quc8sd
     , rcxpcp.quefch
     , rcxpcp.quc9sd
     , rcxpcp.qunaaz
     , rcxpcp.quddsd
     , rcxpcp.qudesd
     , rcxpcp.qudfsd
     , rcxpcp.qudgsd
     , rcxpcp.qudasd
     , rcxpcp.qus8bu
     , rcxpcp.qus9bu
     , rcxpcp.quneaz
     , rcxpcp.qunfaz
     , rcxpcp.qudhsd
     , rcxpcp.qunbaz
     , rcxpcp.quncaz
     , rcxpcp.qudisd
     , rcxpcp.quegch
     , rcxpcp.quywiz
     , rcxpcp.qundaz
     , rcxpcp.qudjsd
     , rcxpcp.qutabu
     , rcxpcp.qungaz
     , rcxpcp.qutbbu
     , rcxpcp.qunhaz
     , rcxpcp.qutcbu
     , rcxpcp.quniaz
     , rcxpcp.qutdbu
     , rcxpcp.qunjaz
     , rcxpcp.qutebu
     , rcxpcp.qunkaz
     , rcxpcp.qutfbu
     , rcxpcp.qutgbu
     , rcxpcp.qudksd
     , rcxpcp.qudlsd
     , rcxpcp.qudmsd
     , rcxpcp.qudnsd
     , rcxpcp.qudosd
     , rcxpcp.quthbu
     , rcxpcp.qunxaz
     , rcxpcp.quyxiz
     , rcxpcp.qunyaz
     , rcxpcp.qunzaz
     , rcxpcp.quyyiz
     , rcxpcp.qun0az
     , rcxpcp.qun1az
     , rcxpcp.quyziz
     , rcxpcp.qun2az
     , rcxpcp.quojqw
     , rcxpcp.quokqw
     , rcxpcp.quolqw
     , rcxpcp.qun3az
     , rcxpcp.quomqw
     , rcxpcp.quonqw
     , rcxpcp.quooqw
     , rcxpcp.qun4az
     , rcxpcp.quopqw
     , rcxpcp.quoqqw
     , rcxpcp.quorqw
     , rcxpcp.quosqw
     , rcxpcp.quotqw
     , rcxpcp.quouqw
     , rcxpcp.qudqsd
     , rcxpcp.qudpsd
     , rcxpcp.quy0iz
     , rcxpcp.quy1iz
     , rcxpcp.quehch
     , rcxpcp.qufysd
     , rcxpcp.qufzsd
     , rcxpcp.quakvn
     , rcxpcp.qusvcg
     , rcxpcp.qut8tx
     , rcxpcp.qualvn
     , rcxpcp.quadvn
     , rcxpcp.quswcg
     , rcxpcp.qut9tx
     , rcxpcp.quaevn
  FROM clmprdext.rcex1p  rcex1p
     , clmprdfil.rctcdp  rctcdp
     , clmprdfil.rcxpcp  rcxpcp
 WHERE rcxpcp.qus5bu = rctcdp.dqp2nb and rcxpcp.qus6bu = rctcdp.dqoinb and rcxpcp.qus5bu = rcex1p.rxclaimnbr and rcxpcp.qus6bu = rcex1p.clmseqnbr and to_char(rcxpcp.quswcg,'YY-MM-DD') >= '21-05-31' AND to_char(rcxpcp.quswcg,'YY-MM-DD') <= '22-10-13' limit 10
